# -*- coding: utf-8 -*-
"""1_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/BioDecodingLab/3D-HepaticNuclei-Classifier/blob/main/notebooks/1_preprocessing.ipynb
"""

import os
import tifffile
import numpy as np
from skimage.measure import label, regionprops

# Clase para cargar las imágenes, las máscaras y las etiquetas
class ImageDataset:
    def __init__(self, image_paths, labels_paths, class_paths):
        if len(image_paths) != len(class_paths):
            raise ValueError("Las rutas de imágenes y máscaras deben coincidir.")
        self.image_paths = image_paths
        self.labels_paths = labels_paths
        self.class_paths = class_paths

    def load_image(self, index=0):
        return tifffile.imread(self.image_paths[index])

    def load_labels(self, index=0):
        return tifffile.imread(self.labels_paths[index])

    def load_class(self, index=0):
        return tifffile.imread(self.class_paths[index])

    def __len__(self):
        return len(self.image_paths)

# Función para verificar si una región toca el borde de la imagen y exlcuir las celulas
def _touches_border_3d(bbox, shape_zyx, border_margin=0):
    min_z, min_y, min_x, max_z, max_y, max_x = bbox
    Z, Y, X = shape_zyx
    if min_z <= border_margin or min_y <= border_margin or min_x <= border_margin:
        return True
    if max_z >= (Z - border_margin) or max_y >= (Y - border_margin) or max_x >= (X - border_margin):
        return True
    return False

def create_datasets(test_id, base_path):
    """
    Create training and testing ImageDataset objects for leave-one-out validation.

    Parameters
    ----------
    test_id : int
        Image ID used for testing (e.g., 1,2,3,4,5)
    base_path : str
        Base directory containing image_train, class_train, labels_train folders

    Returns
    -------
    dataset_train : ImageDataset
    dataset_test : ImageDataset
    """

    all_ids = [1, 2, 3, 4, 5]
    train_ids = [i for i in all_ids if i != test_id]

    image_train_paths = [f"{base_path}/image/{i}.tif" for i in train_ids]
    class_train_paths = [f"{base_path}/class/{i}.tif" for i in train_ids]
    labels_train_paths = [f"{base_path}/labels/{i}.tif" for i in train_ids]

    image_test_paths = [f"{base_path}/image/{test_id}.tif"]
    class_test_paths = [f"{base_path}/class/{test_id}.tif"]
    labels_test_paths = [f"{base_path}/labels/{test_id}.tif"]

    dataset_train = ImageDataset(
        image_paths=image_train_paths,
        class_paths=class_train_paths,
        labels_paths=labels_train_paths
    )

    dataset_test = ImageDataset(
        image_paths=image_test_paths,
        class_paths=class_test_paths,
        labels_paths=labels_test_paths
    )

    return dataset_train, dataset_test

# Función para guardar los parches generados
def save_bbox_patches(image3d, labels_3d, classes_3d, output_dir, border_margin=0, min_voxels=0):
    os.makedirs(output_dir, exist_ok=True)

    # Identificamos las clases presentes, excluyendo el fondo (valor 0)
    classes_present = np.unique(classes_3d)
    classes_present = classes_present[classes_present != 0]

    # Crear carpeta para cada clase
    for class_value in classes_present:
        print(f"Procesando clase: {class_value}")
        label_folder = os.path.join(output_dir, f"label_{class_value}")
        os.makedirs(label_folder, exist_ok=True)

        # Obtener las propiedades de las regiones
        props_image = regionprops(labels_3d, intensity_image=image3d)
        props_class = regionprops(labels_3d, intensity_image=classes_3d)
        idx = 0

        # Iteramos sobre cada región y clase
        for region, region_cls in zip(props_image, props_class):
            label = region.label
            if min_voxels > 0 and region.area < min_voxels:
                continue
            if _touches_border_3d(region.bbox, image3d.shape, border_margin=border_margin):
                continue

            # Obtenemos las intensidades y la clase de la región
            intensities = region_cls.intensity_image
            current_class = np.amax(np.unique(intensities[intensities != 0]))

            # Crear la carpeta para la clase específica si no existe
            label_folder = os.path.join(output_dir, f"label_{current_class}")
            os.makedirs(label_folder, exist_ok=True)

            # Extraemos la imagen de la región
            img = region.image_intensity.astype(np.float32)
            mask = region.image_filled.astype(np.uint8)
            masked_img = np.zeros_like(img)
            masked_img[mask > 0] = img[mask > 0]

            # Guardamos la imagen con un nombre único
            img_save_path = os.path.join(label_folder, f"cell_{idx}_img.tif")
            tifffile.imwrite(img_save_path, masked_img)

            if idx % 100 == 0:
                print(f"Guardando: {img_save_path}")
            idx += 1

    print(f"Parches guardados correctamente en: {output_dir}")

### Calculations:

input_dir = "/content/drive/MyDrive/tesis"
out_dir = "/content/drive/MyDrive/tesis/patches"
os.makedirs(out_dir, exist_ok=True)

for test_id in [1,2,3,4,5]:
    dataset_train, dataset_test = create_datasets(test_id, input_dir)
    print(f"Test image: {test_id}")

  out_folder_train = os.path.join(out_dir, f"trains_{test_id}")
  os.makedirs(out_folder_train, exist_ok=True)
  out_folder_test = os.path.join(out_dir, f"tests_{test_id}")
  os.makedirs(out_folder_test, exist_ok=True)


  # Procesar las imágenes de train
  for i in range(len(dataset_train)):
      image_train = dataset_train.load_image(i)
      labels_train = dataset_train.load_labels(i)
      classes_train = dataset_train.load_class(i)

      save_bbox_patches(
          image_train,
          labels_train,
          classes_train,
          output_dir=out_folder_train",
          border_margin=3
      )

  # Procesar las imágenes de test
  for i in range(len(dataset_test)):
      image_test = dataset_test.load_image(i)
      labels_test = dataset_test.load_labels(i)
      classes_test = dataset_test.load_class(i)

      save_bbox_patches(
          image_test,
          labels_test,
          classes_test,
          output_dir=out_folder_test,
          border_margin=3
      )

