# -*- coding: utf-8 -*-
"""2_embedding_extraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/BioDecodingLab/3D-HepaticNuclei-Classifier/blob/main/notebooks/2_embedding_extraction.ipynb
"""
import sys
sys.path.append("/medicina/hmorales/projects/Nuclei3DClassification/code/3DINO")

import os, glob, random
import numpy as np
import torch
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import tifffile as tiff
import matplotlib.pyplot as plt
import skimage
from pathlib import Path
from tqdm import tqdm
from dinov2.eval.setup import build_model_for_eval
from dinov2.configs import load_and_merge_config_3d

from dataset_helper import *

import time

#print("Pausing for 1 hour...")
#time.sleep(1200)  # 3600 seconds = 1 hour
#print("Resuming...")

#----------------------------------------------------------------
# Input
#----------------------------------------------------------------

patches_dir  =  Path("/medicina/hmorales/projects/Nuclei3DClassification/data/patches/")
out_dir_aug = Path("/medicina/hmorales/projects/Nuclei3DClassification/data/embedding_aug_2000/")
target_per_label = 2000

save_embedings_raw = False
out_dir = Path("/medicina/hmorales/projects/Nuclei3DClassification/data/embedding/")

save_augmented_examples = False
test_aug_dir = Path("/medicina/hmorales/projects/Nuclei3DClassification/data/patches_test_aug/")


labels = [1,2,3,4,5]
target_DHW0 = (70,70,70)
target_DHW  = (112,112,112)

batch_size = 256
num_workers = 48
SEED = 42

config_file = "/medicina/hmorales/projects/Nuclei3DClassification/code/3DINO/dinov2/configs/train/vit3d_highres"
pretrained_weights = "/medicina/hmorales/projects/Nuclei3DClassification/data/3dino_vit_weights.pth"


# Create ouput dir
test_aug_dir.mkdir(parents=True, exist_ok=True)
out_dir.mkdir(parents=True, exist_ok=True)
out_dir_aug.mkdir(parents=True, exist_ok=True)



def seed_everything(seed=SEED):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

seed_everything(SEED)

#----------------------------------------------------------------
# Helper functions
#----------------------------------------------------------------


def seed_worker(worker_id):
    worker_seed = SEED + worker_id
    np.random.seed(worker_seed)
    random.seed(worker_seed)


def extract_embeddings(
    dataset,
    model,
    save_path,
    batch_size,
    num_workers,
    device,
    worker_init_fn=None,
    generator=None,
    flatten_output=False,
    use_multi_gpu=True
):
    """
    Extract embeddings for all samples in a dataset and save them to disk.

    Parameters
    ----------
    dataset : torch.utils.data.Dataset
        Dataset returning (x, y, path).
    model : torch.nn.Module
        Model used to extract embeddings.
    save_path : str
        Output .npz file path.
    batch_size : int
        Batch size for inference.
    num_workers : int
        Number of workers for DataLoader.
    device : torch.device
        Device for inference.
    worker_init_fn : callable, optional
        Worker init function for reproducibility.
    generator : torch.Generator, optional
        Generator for reproducibility.
    flatten_output : bool, default=False
        If True, flatten model outputs to shape (B, -1).
    use_multi_gpu : bool, default=False
        If True and multiple CUDA GPUs are available, wrap model with DataParallel.

    Returns
    -------
    embeddings : np.ndarray
        Extracted embeddings.
    labels : np.ndarray
        Corresponding labels.
    """

    # -----------------------------
    # Multi-GPU support (simple)
    # -----------------------------
    if use_multi_gpu and device.type == "cuda" and torch.cuda.device_count() > 1:
        print(f"Using {torch.cuda.device_count()} GPUs with DataParallel")
        model = torch.nn.DataParallel(model)

    model = model.to(device)

    loader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=num_workers,
        pin_memory=(device.type == "cuda"),
        worker_init_fn=worker_init_fn,
        generator=generator
    )

    model.eval()

    all_emb = []
    all_y = []
    all_paths = []

    pbar = tqdm(total=len(dataset), desc="Extracting embeddings", unit="sample")

    with torch.no_grad():
        for x, y, paths in loader:
            x = x.to(device, non_blocking=True)

            out = model(x)

            if not torch.is_tensor(out):
                raise TypeError(f"Expected model output to be a torch.Tensor, got {type(out)}")

            if out.shape[0] != x.shape[0]:
                raise ValueError(
                    f"Output batch dimension {out.shape[0]} does not match input batch size {x.shape[0]}"
                )

            if flatten_output and out.ndim > 2:
                out = out.flatten(start_dim=1)

            all_emb.append(out.detach().cpu().numpy())

            if torch.is_tensor(y):
                all_y.append(y.detach().cpu().numpy())
            else:
                all_y.append(np.asarray(y))

            all_paths.extend(list(paths))

            # update by number of processed samples
            batch_n = x.size(0)
            pbar.update(batch_n)

            # show GPU memory
            if device.type == "cuda":
                mem_alloc = torch.cuda.memory_allocated(device) / (1024 ** 2)
                mem_reserved = torch.cuda.memory_reserved(device) / (1024 ** 2)
                pbar.set_postfix({
                    "GPU_alloc_MB": f"{mem_alloc:.1f}",
                    "GPU_reserved_MB": f"{mem_reserved:.1f}"
                })

    pbar.close()

    if len(all_emb) == 0:
        raise ValueError("Dataset is empty. No embeddings were extracted.")

    embeddings = np.concatenate(all_emb, axis=0)
    labels = np.concatenate(all_y, axis=0)

    save_dir = os.path.dirname(save_path)
    if save_dir:
        os.makedirs(save_dir, exist_ok=True)

    np.savez_compressed(
        save_path,
        embeddings=embeddings,
        labels=labels,
        paths=np.asarray(all_paths, dtype=str)
    )

    print(f"Embeddings: {embeddings.shape} | Labels: {labels.shape} | Saved to: {save_path}")

    return embeddings, labels

# -----------------------------
## Test data augmentation
# -----------------------------


def save_aug_preview(dataset_noaug, dataset_aug, out_dir, n_examples=10, extra_name=""):
    """
    Save paired preview volumes from non-augmented and augmented datasets.

    Parameters
    ----------
    dataset_noaug : Dataset
        Dataset without augmentation.
    dataset_aug : Dataset
        Dataset with augmentation.
    out_dir : str or Path
        Output directory.
    n_examples : int, default=10
        Number of examples to save.
    """
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    if len(dataset_noaug) != len(dataset_aug):
        raise ValueError(
            f"Dataset size mismatch: len(dataset_noaug)={len(dataset_noaug)} "
            f"!= len(dataset_aug)={len(dataset_aug)}"
        )

    picks = np.linspace(
        0,
        len(dataset_noaug) - 1,
        num=min(n_examples, len(dataset_noaug)),
        dtype=int
    )

    for i, idx in enumerate(picks):
        x0, y0, p0 = dataset_noaug[idx]
        x1, y1, p1 = dataset_aug[idx]

        if y0 != y1:
            raise ValueError(f"Label mismatch at idx={idx}: {y0} vs {y1}")

        if p0 != p1:
            raise ValueError(f"Path mismatch at idx={idx}: {p0} vs {p1}")

        v0 = x0.squeeze(0).numpy()  # (D, H, W)
        v1 = x1.squeeze(0).numpy()

        stem = Path(p0).stem

        tiff.imwrite(out_dir / f"noaug_{i:02d}_{extra_name}_{stem}_label{y0}.tif", v0)
        tiff.imwrite(out_dir / f"aug_{i:02d}_{extra_name}__{stem}_label{y0}.tif", v1)

    print(f"Saved {len(picks)} preview pairs in: {out_dir}")


# Calculations

if save_augmented_examples:
  # Get all subfolders
  subfolders = sorted([p for p in patches_dir.iterdir() if p.is_dir()])

  for img_folder in subfolders:
    print(f"\nProcessing folder: {img_folder.name}")

    # Create non-augmented dataset
    dataset_noaug = Tif3DDatasetSingle(
        base_dir=str(img_folder),
        labels=labels,
        target_dhw0=target_DHW0,
        target_dhw=target_DHW,
        do_aug=False,
        seed=SEED,
    )
    # Create augmented dataset
    dataset_aug = Tif3DDatasetSingle(
        base_dir=str(img_folder),
        labels=labels,
        target_dhw0=target_DHW0,
        target_dhw=target_DHW,
        do_aug=True,
        seed=SEED,
    )

    print(f"Found {len(dataset_noaug)} patches to augment -> {len(dataset_aug)} ")

    save_aug_preview(dataset_noaug, dataset_aug, test_aug_dir, n_examples=5, extra_name=img_folder.name)

# -----------------------------
## Get embedings
# -----------------------------

# Load model

cfg = load_and_merge_config_3d(config_file)
model = build_model_for_eval(cfg, pretrained_weights)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)
model.eval()

print("Model ready at:", device)

g = torch.Generator()
g.manual_seed(SEED)

# Calculations of embedings

# Get all subfolders
subfolders = sorted([p for p in patches_dir.iterdir() if p.is_dir()])

for img_folder in subfolders:
  print(f"\nProcessing folder: {img_folder.name}")

  # Create non-augmented dataset
  dataset_noaug = Tif3DDatasetSingle(
      base_dir=str(img_folder),
      labels=labels,
      target_dhw0=target_DHW0,
      target_dhw=target_DHW,
      do_aug=False,
      seed=SEED,
  )

  # Create augmented dataset
  dataset_aug = Tif3DDatasetSingle(
      base_dir=str(img_folder),
      labels=labels,
      target_dhw0=target_DHW0,
      target_dhw=target_DHW,
      do_aug=True,
      target_per_label=target_per_label,
      seed=SEED,
  )

  print(f"Found {len(dataset_noaug)} original patches and {len(dataset_aug)} augmented ")

  if save_embedings_raw: 
      save_path = out_dir / f"{img_folder.name}.npz"
      embeddings, labels_emb = extract_embeddings(dataset_noaug, model, save_path, batch_size, num_workers, device, worker_init_fn=seed_worker, generator=g)
      print(f"Saved at: {save_path}")


  save_path_aug = out_dir_aug / f"{img_folder.name}_{target_per_label}_samples_aug.npz"
  embeddings_aug, labels_emb_aug = extract_embeddings(dataset_aug, model, save_path_aug,  batch_size, num_workers, device, worker_init_fn=seed_worker, generator=g)
  print(f"Saved at: {save_path_aug}")

