# -*- coding: utf-8 -*-
"""3D train test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17zB9VF5PtuFYL6WmaPLfnEOZ9Sk0XS0I
"""

!pip -q install tifffile scikit-image

from google.colab import drive
drive.mount('/content/drive')

import os
import tifffile
import numpy as np
from skimage.measure import regionprops

def _touches_border_3d(bbox, shape_zyx, border_margin=0):
    min_z, min_y, min_x, max_z, max_y, max_x = bbox
    Z, Y, X = shape_zyx

    if min_z <= border_margin or min_y <= border_margin or min_x <= border_margin:
        return True
    if max_z >= (Z - border_margin) or max_y >= (Y - border_margin) or max_x >= (X - border_margin):
        return True
    return False


def save_bbox_patches(
    image3d,
    labels_3d,
    classes_3d,
    output_dir,
    image_id="img",
    border_margin=0,
    min_voxels=0,
    start_idx=0,
):
    """
    Guarda parches en output_dir/label_<class>/ con nombre único:
    {image_id}_cell_{idx}.tif

    Retorna el siguiente idx global.
    """
    os.makedirs(output_dir, exist_ok=True)

    classes_present = np.unique(classes_3d)
    classes_present = classes_present[classes_present != 0]
    for class_value in classes_present:
        os.makedirs(os.path.join(output_dir, f"label_{int(class_value)}"), exist_ok=True)

    props_image = regionprops(labels_3d, intensity_image=image3d)
    props_class = regionprops(labels_3d, intensity_image=classes_3d)

    idx = start_idx

    for region, region_cls in zip(props_image, props_class):
        if min_voxels > 0 and region.area < min_voxels:
            continue

        if _touches_border_3d(region.bbox, image3d.shape, border_margin=border_margin):
            continue

        intensities = region_cls.intensity_image
        nonzero = intensities[intensities != 0]
        if nonzero.size == 0:
            continue

        current_class = int(np.max(nonzero))
        label_folder = os.path.join(output_dir, f"label_{current_class}")
        os.makedirs(label_folder, exist_ok=True)

        img = region.image_intensity.astype(np.float32)
        mask = region.image_filled.astype(np.uint8)

        masked_img = np.zeros_like(img)
        masked_img[mask > 0] = img[mask > 0]

        img_save_path = os.path.join(label_folder, f"{image_id}_cell_{idx:07d}.tif")
        tifffile.imwrite(img_save_path, masked_img)

        if idx % 50 == 0:
            print(f"[{image_id}] saving: {img_save_path}")

        idx += 1

    return idx


def list_tifs(folder):
    return sorted([
        f for f in os.listdir(folder)
        if f.lower().endswith(".tif") or f.lower().endswith(".tiff")
    ])


def process_split(image_dir, labels_dir, class_dir, output_dir, split_name="split", border_margin=0, min_voxels=0):
    """
    Procesa TODO un split (train o test) y guarda en output_dir/label_k
    sin sobrescribir usando nombre del archivo como image_id + contador global del split.
    """
    os.makedirs(output_dir, exist_ok=True)

    files = list_tifs(image_dir)
    print(f"\n=== {split_name.upper()} ===")
    print("Total imágenes encontradas:", len(files))
    print("Ejemplo:", files[:5])

    global_idx = 0

    for fname in files:
        img_path = os.path.join(image_dir, fname)
        lab_path = os.path.join(labels_dir, fname)
        cls_path = os.path.join(class_dir, fname)

        if not os.path.exists(lab_path):
            print(f"Falta labels para {fname} -> {lab_path}")
            continue
        if not os.path.exists(cls_path):
            print(f"Falta class para {fname} -> {cls_path}")
            continue

        image_id = f"{split_name}_{os.path.splitext(fname)[0]}"  # evita choque train vs test

        image3d   = tifffile.imread(img_path)
        labels3d  = tifffile.imread(lab_path)
        classes3d = tifffile.imread(cls_path)

        print(f"Procesando: {fname} | max(class)={np.max(classes3d)} | max(labels)={np.max(labels3d)}")

        global_idx = save_bbox_patches(
            image3d,
            labels3d,
            classes3d,
            output_dir=output_dir,
            image_id=image_id,
            border_margin=border_margin,
            min_voxels=min_voxels,
            start_idx=global_idx
        )

    print(f"{split_name} listo. Total parches guardados: {global_idx}")
    return global_idx

# ===== TRAIN =====
train_image_dir  = "/content/drive/MyDrive/tesis/image_train"
train_labels_dir = "/content/drive/MyDrive/tesis/labels_train"
train_class_dir  = "/content/drive/MyDrive/tesis/class_train"

# ===== TEST =====
test_image_dir  = "/content/drive/MyDrive/tesis/image_test"
test_labels_dir = "/content/drive/MyDrive/tesis/labels_test"
test_class_dir  = "/content/drive/MyDrive/tesis/class_test"

# ===== OUTPUTS =====
patches_train_dir = "/content/drive/MyDrive/tesis/patches_train"
patches_test_dir  = "/content/drive/MyDrive/tesis/patches_test"

border_margin = 3
min_voxels = 0

train_total = process_split(
    train_image_dir, train_labels_dir, train_class_dir,
    output_dir=patches_train_dir,
    split_name="train",
    border_margin=border_margin,
    min_voxels=min_voxels
)

test_total = process_split(
    test_image_dir, test_labels_dir, test_class_dir,
    output_dir=patches_test_dir,
    split_name="test",
    border_margin=border_margin,
    min_voxels=min_voxels
)

print("\nRESUMEN:")
print("Train patches:", train_total)
print("Test patches:", test_total)

def count_patches_by_label(root_dir):
    if not os.path.exists(root_dir):
        print("No existe:", root_dir)
        return

    folders = sorted([d for d in os.listdir(root_dir) if d.startswith("label_")])
    print("\nConteo en:", root_dir)
    for d in folders:
        path = os.path.join(root_dir, d)
        n = len([f for f in os.listdir(path) if f.lower().endswith((".tif",".tiff"))])
        print(f"{d}: {n}")

count_patches_by_label(patches_train_dir)
count_patches_by_label(patches_test_dir)