# -*- coding: utf-8 -*-
"""6_box_plot_and_statistics_all_models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XRXK7XlVsiXup_YXWZAOTloy1VREFcgB
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display


results_root = "/content/drive/MyDrive/tesis/results"

# Reload the summary table
summary_df = pd.read_csv(os.path.join(results_root, "boxplot_metrics_summary_TEST_CORRECT.csv"))

plots_output_folder = os.path.join(results_root, "boxplots_pretty_test_final")
os.makedirs(plots_output_folder, exist_ok=True)

# 1. Labels
label_map = {
    "Logistic Regression": "LogReg",
    "Random Forest": "RF",
    "Support Vector Machine": "SVM",
    "MLP": "MLP"
}

def make_experiment_label(model, augmentation):
    short_model = label_map.get(str(model), str(model))
    aug = str(augmentation).strip().lower()

    if aug == "no_aug":
        return short_model
    return f"{short_model} +{aug}"

summary_df["model"] = summary_df["model"].astype(str)
summary_df["augmentation"] = summary_df["augmentation"].astype(str).str.strip().str.lower()

valid_augmentations = ["no_aug", "100", "500", "1000", "2000"]
summary_df = summary_df[summary_df["augmentation"].isin(valid_augmentations)].copy()

summary_df["experiment_label"] = [
    make_experiment_label(m, a)
    for m, a in zip(summary_df["model"], summary_df["augmentation"])
]

experiment_order = [
    "LogReg", "LogReg +100", "LogReg +500", "LogReg +1000", "LogReg +2000",
    "RF", "RF +100", "RF +500", "RF +1000", "RF +2000",
    "SVM", "SVM +100", "SVM +500", "SVM +1000", "SVM +2000",
    "MLP", "MLP +100", "MLP +500", "MLP +1000", "MLP +2000"
]

summary_df = summary_df[summary_df["experiment_label"].isin(experiment_order)].copy()

# Ensure numeric
for col in ["roc_auc_macro_ovr", "f1_macro", "f1_weighted", "balanced_accuracy"]:
    summary_df[col] = pd.to_numeric(summary_df[col], errors="coerce")

summary_df = summary_df.dropna(
    subset=["experiment_label", "roc_auc_macro_ovr", "f1_macro", "f1_weighted", "balanced_accuracy"]
).copy()

print("Rows available for plotting:", len(summary_df))
print("\nCounts per experiment label:")
display(summary_df["experiment_label"].value_counts().sort_index())

# 2. Boxplot function
def make_pretty_boxplot(data, y_col, y_label, title, output_name):
    plot_df = data[["experiment_label", y_col]].dropna().copy()

    print(f"\nPlotting {y_col}")
    display(plot_df.groupby("experiment_label").size().reset_index(name="n"))

    if plot_df.empty:
        raise ValueError(f"No data available for plotting {y_col}")

    plt.figure(figsize=(20, 8))

    ax = sns.boxplot(
        data=plot_df,
        x="experiment_label",
        y=y_col,
        order=experiment_order,
        width=0.58,
        showcaps=True,
        showfliers=False,
        boxprops=dict(facecolor="#cfe8ff", edgecolor="#1f4e79", linewidth=1.8),
        whiskerprops=dict(color="#1f4e79", linewidth=1.8),
        capprops=dict(color="#1f4e79", linewidth=1.8),
        medianprops=dict(color="#08306b", linewidth=2.5)
    )

    sns.stripplot(
        data=plot_df,
        x="experiment_label",
        y=y_col,
        order=experiment_order,
        color="#0b3d91",
        size=4,
        alpha=0.7,
        jitter=0.16,
        ax=ax
    )

    ax.set_xlabel("Model and augmentation setting", fontsize=13, fontweight="bold")
    ax.set_ylabel(y_label, fontsize=13, fontweight="bold")
    ax.set_title(title, fontsize=15, fontweight="bold", pad=14)

    plt.xticks(rotation=45, ha="right", fontsize=10)
    plt.yticks(fontsize=10)

    ax.grid(axis="y", linestyle="--", alpha=0.25)
    ax.grid(axis="x", visible=False)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    plt.tight_layout()

    save_path = os.path.join(plots_output_folder, output_name)
    plt.savefig(save_path, format="svg", bbox_inches="tight", dpi=300)
    plt.show()
    plt.close()

    print(f"Saved plot: {save_path}")

# 3. Generate the 4 boxplots
make_pretty_boxplot(
    summary_df,
    y_col="roc_auc_macro_ovr",
    y_label="Macro AUC OVR per fold",
    title="Test Macro AUC by Model and Augmentation",
    output_name="test_macro_auc_boxplot_pretty.svg"
)

make_pretty_boxplot(
    summary_df,
    y_col="f1_macro",
    y_label="Macro F1 score per fold",
    title="Test Macro F1 Score by Model and Augmentation",
    output_name="test_f1_macro_boxplot_pretty.svg"
)

make_pretty_boxplot(
    summary_df,
    y_col="f1_weighted",
    y_label="Weighted F1 score per fold",
    title="Test Weighted F1 Score by Model and Augmentation",
    output_name="test_f1_weighted_boxplot_pretty.svg"
)

make_pretty_boxplot(
    summary_df,
    y_col="balanced_accuracy",
    y_label="Balanced accuracy per fold",
    title="Test Balanced Accuracy by Model and Augmentation",
    output_name="test_balanced_accuracy_boxplot_pretty.svg"
)

# FRIEDMAN + POST HOC WILCOXON + HOLM
# Metric: f1_macro
# Baseline post hoc: SVM +1000


import os
import numpy as np
import pandas as pd
from scipy.stats import friedmanchisquare, wilcoxon, rankdata
from statsmodels.stats.multitest import multipletests
from IPython.display import display


# 1. Upload file

input_csv = "/content/drive/MyDrive/tesis/results/boxplot_metrics_summary_TEST_CORRECT.csv"
output_dir = "/content/drive/MyDrive/tesis/results"

df = pd.read_csv(input_csv)

print("Archivo cargado:")
print(input_csv)
display(df.head())


# 2. Reconstruct experiment labels

label_map = {
    "Logistic Regression": "LogReg",
    "Random Forest": "RF",
    "Support Vector Machine": "SVM",
    "MLP": "MLP"
}

def make_experiment_label(model, augmentation):
    short_model = label_map.get(str(model).strip(), str(model).strip())
    aug = str(augmentation).strip().lower()
    if aug == "no_aug":
        return short_model
    return f"{short_model} +{aug}"

df["model"] = df["model"].astype(str).str.strip()
df["augmentation"] = df["augmentation"].astype(str).str.strip().str.lower()
df["fold"] = pd.to_numeric(df["fold"], errors="coerce")
df["f1_macro"] = pd.to_numeric(df["f1_macro"], errors="coerce")

df["experiment_label"] = [
    make_experiment_label(m, a)
    for m, a in zip(df["model"], df["augmentation"])
]


# 3. Select metric and baseline

metric_col = "f1_macro"
baseline = "SVM +1000"

experiment_order = [
    "LogReg", "LogReg +100", "LogReg +500", "LogReg +1000", "LogReg +2000",
    "RF", "RF +100", "RF +500", "RF +1000", "RF +2000",
    "SVM", "SVM +100", "SVM +500", "SVM +1000", "SVM +2000",
    "MLP", "MLP +100", "MLP +500", "MLP +1000", "MLP +2000"
]

df = df[df["experiment_label"].isin(experiment_order)].copy()
df = df.dropna(subset=["fold", metric_col, "experiment_label"]).copy()

print("\nMétrica seleccionada:", metric_col)
print("Baseline:", baseline)


# 4. Folded paired matrix

pivot_df = df.pivot_table(
    index="fold",
    columns="experiment_label",
    values=metric_col,
    aggfunc="mean"
)

available_cols = [col for col in experiment_order if col in pivot_df.columns]
pivot_df = pivot_df[available_cols]

# Keep only complete folds
pivot_df = pivot_df.dropna(axis=0, how="any")

print("\nMatriz pareada:")
display(pivot_df)

print("Shape:", pivot_df.shape)

if pivot_df.shape[0] < 2:
    raise ValueError("No hay suficientes folds para hacer el análisis.")

if pivot_df.shape[1] < 3:
    raise ValueError("Se necesitan al menos 3 experimentos para Friedman.")

if baseline not in pivot_df.columns:
    raise ValueError(f"No se encontró el baseline '{baseline}'.")


# 5. Descriptive statistics per experiment

summary_df = pd.DataFrame({
    "experiment": pivot_df.columns,
    "mean_f1_macro": pivot_df.mean(axis=0).values,
    "std_f1_macro": pivot_df.std(axis=0, ddof=1).values,
    "median_f1_macro": pivot_df.median(axis=0).values
}).sort_values("mean_f1_macro", ascending=False).reset_index(drop=True)

print("\nResumen descriptivo:")
display(summary_df)


# 6. Friedman

friedman_stat, friedman_p = friedmanchisquare(
    *[pivot_df[col].values for col in pivot_df.columns]
)

# average ranks (lower rank = better)
ranks_per_fold = pivot_df.apply(
    lambda row: rankdata(-row.values, method="average"),
    axis=1,
    result_type="expand"
)
ranks_per_fold.columns = pivot_df.columns

avg_ranks_df = pd.DataFrame({
    "experiment": ranks_per_fold.columns,
    "average_rank": ranks_per_fold.mean(axis=0).values
}).sort_values("average_rank", ascending=True).reset_index(drop=True)

friedman_results = pd.DataFrame([{
    "metric": metric_col,
    "n_folds": pivot_df.shape[0],
    "n_experiments": pivot_df.shape[1],
    "friedman_statistic": friedman_stat,
    "friedman_p_value": friedman_p
}])

print("\nResultado Friedman:")
display(friedman_results)

print("\nRangos promedio Friedman:")
display(avg_ranks_df)


# 7. Post hoc: Wilcoxon baseline vs all

baseline_values = pivot_df[baseline].values
posthoc_rows = []

for exp in pivot_df.columns:
    if exp == baseline:
        continue

    comparison_values = pivot_df[exp].values

    if np.allclose(baseline_values, comparison_values):
        stat = 0.0
        p_value = 1.0
    else:
        try:
            stat, p_value = wilcoxon(
                baseline_values,
                comparison_values,
                zero_method="wilcox",
                alternative="two-sided",
                mode="auto"
            )
        except ValueError:
            stat = np.nan
            p_value = 1.0

    baseline_mean = np.mean(baseline_values)
    comparison_mean = np.mean(comparison_values)
    mean_difference = baseline_mean - comparison_mean

    posthoc_rows.append({
        "baseline": baseline,
        "comparison": exp,
        "baseline_mean": baseline_mean,
        "comparison_mean": comparison_mean,
        "mean_difference": mean_difference,
        "wilcoxon_statistic": stat,
        "p_value_raw": p_value
    })

posthoc_df = pd.DataFrame(posthoc_rows)


# 8. Holm Correction

reject, pvals_corrected, _, _ = multipletests(
    posthoc_df["p_value_raw"].values,
    alpha=0.05,
    method="holm"
)

posthoc_df["p_value_holm"] = pvals_corrected
posthoc_df["reject_h0_holm"] = reject

def interpret(row):
    if row["reject_h0_holm"]:
        if row["mean_difference"] > 0:
            return f"{row['baseline']} mejor"
        elif row["mean_difference"] < 0:
            return f"{row['comparison']} mejor"
        else:
            return "diferencia significativa"
    return "sin diferencia significativa"

posthoc_df["interpretation"] = posthoc_df.apply(interpret, axis=1)

posthoc_df = posthoc_df.sort_values(
    ["p_value_holm", "p_value_raw", "comparison"]
).reset_index(drop=True)

print("\nPost hoc Wilcoxon + Holm:")
display(posthoc_df)


# 9. Save results

summary_output = os.path.join(output_dir, "summary_f1_macro_by_experiment.csv")
friedman_output = os.path.join(output_dir, "friedman_f1_macro.csv")
ranks_output = os.path.join(output_dir, "friedman_average_ranks_f1_macro.csv")
posthoc_output = os.path.join(output_dir, "posthoc_wilcoxon_holm_SVM1000_f1_macro.csv")

summary_df.to_csv(summary_output, index=False)
friedman_results.to_csv(friedman_output, index=False)
avg_ranks_df.to_csv(ranks_output, index=False)
posthoc_df.to_csv(posthoc_output, index=False)

print("\nArchivos guardados:")
print(summary_output)
print(friedman_output)
print(ranks_output)
print(posthoc_output)