# -*- coding: utf-8 -*-
"""7_SHAP_interpretability_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rMboaqcjUA6kPahzctIkmzjQsesRfJ1f
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import json
import joblib
from pathlib import Path

try:
    from sklearn.pipeline import Pipeline
except:
    Pipeline = None

MODEL_DIR = Path("/content/drive/MyDrive/tesis/model")
model_path = MODEL_DIR / "final_model.joblib"

model = joblib.load(model_path)

print("Tipo objeto cargado:", type(model))

if hasattr(model, "best_estimator_"):
    print("Tiene best_estimator_")
    model = model.best_estimator_

print("Tipo modelo final:", type(model))

if isinstance(model, Pipeline):
    print("\nEs un Pipeline")
    print("Steps:")
    for name, step in model.steps:
        print(f"- {name}: {type(step).__name__}")
    est = model.steps[-1][1]
else:
    print("\nNo es Pipeline")
    est = model

print("\nEstimador final:", type(est).__name__)

for attr in ["kernel", "C", "gamma", "probability"]:
    if hasattr(est, attr):
        print(f"{attr}: {getattr(est, attr)}")

print("Tiene predict_proba:", hasattr(model, "predict_proba"))
print("Tiene decision_function:", hasattr(model, "decision_function"))

!pip install -q scikit-learn==1.1.1 shap==0.44.1 joblib

!pip install -q shap

import sklearn, shap, sys
print("Python:", sys.version)
print("scikit-learn:", sklearn.__version__)
print("shap:", shap.__version__)

import numpy as np

train_data = np.load("/content/drive/MyDrive/tesis/model/img_4_1000_samples_aug.npz", allow_pickle=True)
test_data  = np.load("/content/drive/MyDrive/tesis/model/img_4.npz", allow_pickle=True)

X_full = train_data["embeddings"]
y_full = train_data["labels"]

X_test = test_data["embeddings"]
y_test = test_data["labels"]

print("X_full:", X_full.shape)
print("X_test:", X_test.shape)
print("y_test:", y_test.shape)

import shap
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# 1) SEPARATE PARTS OF THE PIPELINE

scaler = model.named_steps["scaler"]
pca = model.named_steps["pca"]
clf = model.named_steps["clf"]


# 2) TRANSFORM DATA TO PCA SPACE

X_full_scaled = scaler.transform(X_full)
X_test_scaled = scaler.transform(X_test)

X_full_pca = pca.transform(X_full_scaled)
X_test_pca = pca.transform(X_test_scaled)

print("X_full_pca:", X_full_pca.shape)
print("X_test_pca:", X_test_pca.shape)

n_pcs = X_full_pca.shape[1]
pc_names = [f"PC_{i+1:03d}" for i in range(n_pcs)]


# 3) SAMPLING

rng = np.random.RandomState(42)

bg_size = min(40, X_full_pca.shape[0])
ex_size = min(40, X_test_pca.shape[0])

bg_idx = rng.choice(X_full_pca.shape[0], size=bg_size, replace=False)
ex_idx = rng.choice(X_test_pca.shape[0], size=ex_size, replace=False)

X_bg = X_full_pca[bg_idx]
X_ex = X_test_pca[ex_idx]
y_ex = y_test[ex_idx]

print("X_bg:", X_bg.shape)
print("X_ex:", X_ex.shape)


# 4) SHAP

explainer = shap.KernelExplainer(
    clf.predict_proba,
    X_bg,
    feature_names=pc_names
)

raw_shap = explainer.shap_values(X_ex, nsamples=300)


# 5) STANDARDIZE FORMAT

if isinstance(raw_shap, list):
    shap_vals = raw_shap
    is_multiclass = True
else:
    raw_shap = np.array(raw_shap)
    if raw_shap.ndim == 3:
        shap_vals = [raw_shap[:, :, k] for k in range(raw_shap.shape[2])]
        is_multiclass = True
    elif raw_shap.ndim == 2:
        shap_vals = raw_shap
        is_multiclass = False
    else:
        raise ValueError(f"Formato inesperado: {raw_shap.shape}")

print("Multiclase:", is_multiclass)


# 6) GLOBAL IMPORTANCE

if is_multiclass:
    abs_vals = np.mean([np.abs(v) for v in shap_vals], axis=0)
else:
    abs_vals = np.abs(shap_vals)

global_importance = abs_vals.mean(axis=0)

topk = min(20, len(global_importance))
top_idx = np.argsort(global_importance)[::-1][:topk]

df_top = pd.DataFrame({
    "feature": np.array(pc_names)[top_idx],
    "mean_abs_shap": global_importance[top_idx]
})

display(df_top)

plt.figure(figsize=(8, 6))
plt.barh(df_top["feature"][::-1], df_top["mean_abs_shap"][::-1])
plt.title("SHAP global (mean |SHAP|) - TOP componentes PCA - SVM")
plt.xlabel("Importancia")
plt.tight_layout()
plt.show()

# 7) SUMMARY PER CLASS

class_labels = clf.classes_

if is_multiclass:
    class_names = [f"Clase {c}" for c in class_labels]
    for k, cname in enumerate(class_names):
        shap.summary_plot(
            shap_vals[k],
            X_ex,
            feature_names=pc_names,
            max_display=20,
            show=False
        )
        plt.title(f"SHAP summary - {cname}")
        plt.tight_layout()
        plt.show()
else:
    shap.summary_plot(
        shap_vals,
        X_ex,
        feature_names=pc_names,
        max_display=20,
        show=False
    )
    plt.title("SHAP summary - SVM")
    plt.tight_layout()
    plt.show()