# -*- coding: utf-8 -*-
"""Boxplot_stadistic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hCTs7Wr8TzS5XVAJC5ZvRtL90ZzS5pO4
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import json

from scipy.stats import friedmanchisquare, wilcoxon, rankdata
from statsmodels.stats.multitest import multipletests
from IPython.display import display


# ============================================================
# 1. CONFIGURATION
# ============================================================

RESULTS_ROOT = ".../Paper/results 1/results/DINO3D"

FINAL_OUTPUT_DIR = ".../Paper/results 1/results/Resultado_final_DINO3D"

CSV_OUTPUT_DIR = os.path.join(FINAL_OUTPUT_DIR, "csv_tables")
PLOTS_OUTPUT_DIR = os.path.join(FINAL_OUTPUT_DIR, "boxplots_svg")

os.makedirs(FINAL_OUTPUT_DIR, exist_ok=True)
os.makedirs(CSV_OUTPUT_DIR, exist_ok=True)
os.makedirs(PLOTS_OUTPUT_DIR, exist_ok=True)


MODEL_MAP = {
    "logreg": "Logistic Regression",
    "rf": "Random Forest",
    "svm": "Support Vector Machine",
    "mlp": "MLP"
}

LABEL_MAP = {
    "Logistic Regression": "LogReg",
    "Random Forest": "RF",
    "Support Vector Machine": "SVM",
    "MLP": "MLP",
    "logreg": "LogReg",
    "rf": "RF",
    "svm": "SVM",
    "mlp": "MLP"
}

MODEL_ORDER = ["logreg", "rf", "svm", "mlp"]

VALID_AUGMENTATIONS = ["noaug", "100", "500", "1000", "2000", "4000"]

EXPERIMENT_ORDER = [
    "LogReg", "LogReg +100", "LogReg +500", "LogReg +1000", "LogReg +2000", "LogReg +4000",
    "RF", "RF +100", "RF +500", "RF +1000", "RF +2000", "RF +4000",
    "SVM", "SVM +100", "SVM +500", "SVM +1000", "SVM +2000", "SVM +4000",
    "MLP", "MLP +100", "MLP +500", "MLP +1000", "MLP +2000", "MLP +4000"
]

TARGET_METRICS = [
    "accuracy",
    "precision_weighted",
    "recall_weighted",
    "f1_weighted",
    "precision_macro",
    "recall_macro",
    "f1_macro",
    "balanced_accuracy",
    "roc_auc_macro_ovr"
]


# ============================================================
# 2. BOXPLOT SETTINGS
# ============================================================

BOXPLOT_METRICS = {
    "roc_auc_macro_ovr": {
        "ylabel": "Macro AUC OVR per fold",
        "title": "Test Macro AUC by Model and Augmentation",
        "filename": "test_macro_auc_boxplot_0_4_1_0.svg",
        "ylim": (0.4, 1.0)
    },
    "f1_macro": {
        "ylabel": "Macro F1 score per fold",
        "title": "Test Macro F1 Score by Model and Augmentation",
        "filename": "test_f1_macro_boxplot_0_4_0_7.svg",
        "ylim": (0.4, 1)
    },
    "f1_weighted": {
        "ylabel": "Weighted F1 score per fold",
        "title": "Test Weighted F1 Score by Model and Augmentation",
        "filename": "test_f1_weighted_boxplot_0_4_1_0.svg",
        "ylim": (0.4, 1.0)
    },
    "balanced_accuracy": {
        "ylabel": "Balanced accuracy per fold",
        "title": "Test Balanced Accuracy by Model and Augmentation",
        "filename": "test_balanced_accuracy_boxplot_0_4_0_7.svg",
        "ylim": (0.4, 1)
    }
}


# ============================================================
# 3. HELPER FUNCTIONS
# ============================================================

def parse_augmentation(folder_name):
    m = re.match(r"cv_benchmark_results_(.+?)_cv$", folder_name.lower())
    return m.group(1) if m else None


def make_experiment_label(model, augmentation):
    short_model = LABEL_MAP.get(str(model).strip(), str(model).strip())
    aug = str(augmentation).strip().lower()

    if aug == "noaug":
        return short_model

    return f"{short_model} +{aug}"


def find_metrics_summary_file(fold_dir):
    for fname in os.listdir(fold_dir):
        low = fname.lower()

        if low == "metrics_summary" or low == "metrics_summary.csv":
            return os.path.join(fold_dir, fname)

    for fname in os.listdir(fold_dir):
        if "metrics_summary" in fname.lower():
            return os.path.join(fold_dir, fname)

    return None


def read_metrics_summary(file_path):
    try:
        df = pd.read_csv(file_path)
    except Exception:
        df = pd.read_csv(file_path, sep=None, engine="python")

    df.columns = [str(c).strip().lower() for c in df.columns]

    if "split" not in df.columns:
        raise ValueError(f"No existe columna 'split' en {file_path}")

    df["split"] = df["split"].astype(str).str.strip().str.lower()

    test_row = df[df["split"] == "test"]

    if test_row.empty:
        raise ValueError(f"No se encontró fila 'Test' en {file_path}")

    test_row = test_row.iloc[0]

    result = {}

    for metric in TARGET_METRICS:
        result[metric] = pd.to_numeric(test_row.get(metric, None), errors="coerce")

    return result


# ============================================================
# 4. EXTRACT TEST METRICS FROM ALL FOLDS
# ============================================================

rows = []

for folder_name in sorted(os.listdir(RESULTS_ROOT)):
    folder_path = os.path.join(RESULTS_ROOT, folder_name)

    if not os.path.isdir(folder_path):
        continue

    augmentation = parse_augmentation(folder_name)

    if augmentation is None:
        continue

    augmentation = str(augmentation).strip().lower()

    if augmentation not in VALID_AUGMENTATIONS:
        continue

    for model_key in MODEL_ORDER:
        model_dir = os.path.join(folder_path, model_key)

        if not os.path.isdir(model_dir):
            print(f"[WARNING] Model folder not found: {model_dir}")
            continue

        for subfolder in sorted(os.listdir(model_dir)):
            fold_dir = os.path.join(model_dir, subfolder)

            if not os.path.isdir(fold_dir):
                continue

            if not re.match(r"cv_fold_test_img_\d+$", subfolder.lower()):
                continue

            fold_match = re.search(r"(\d+)$", subfolder)
            fold_id = int(fold_match.group(1)) if fold_match else None

            metrics_file = find_metrics_summary_file(fold_dir)

            if metrics_file is None:
                print(f"[WARNING] metrics_summary not found in: {fold_dir}")
                continue

            try:
                metrics = read_metrics_summary(metrics_file)

                row = {
                    "source_folder": folder_name,
                    "model_key": model_key,
                    "model": MODEL_MAP[model_key],
                    "augmentation": augmentation,
                    "fold": fold_id,
                    "split": "Test",
                    "metrics_file": metrics_file
                }

                row.update(metrics)
                rows.append(row)

                print(f"[OK] {folder_name} | {model_key} | fold {fold_id}")

            except Exception as e:
                print(f"[ERROR] {metrics_file}: {e}")


summary_df = pd.DataFrame(rows)

if summary_df.empty:
    raise ValueError("No data extracted. Check folders and metrics_summary files.")


# ============================================================
# 5. CLEAN DATA
# ============================================================

summary_df["model"] = summary_df["model"].astype(str).str.strip()
summary_df["augmentation"] = summary_df["augmentation"].astype(str).str.strip().str.lower()
summary_df["fold"] = pd.to_numeric(summary_df["fold"], errors="coerce")

summary_df["experiment_label"] = [
    make_experiment_label(m, a)
    for m, a in zip(summary_df["model"], summary_df["augmentation"])
]

summary_df = summary_df[summary_df["experiment_label"].isin(EXPERIMENT_ORDER)].copy()

for col in TARGET_METRICS:
    summary_df[col] = pd.to_numeric(summary_df[col], errors="coerce")

summary_df = summary_df.sort_values(
    ["model_key", "augmentation", "fold"]
).reset_index(drop=True)


# ============================================================
# 6. SAVE FULL FOLD-LEVEL CSV
# ============================================================

full_csv_path = os.path.join(
    CSV_OUTPUT_DIR,
    "test_metrics_by_fold_all_experiments.csv"
)

summary_df.to_csv(full_csv_path, index=False, encoding="utf-8-sig")

print("\nSaved full fold-level table:")
print(full_csv_path)

display(summary_df.head())


# ============================================================
# 7. SAVE AGGREGATED SUMMARY CSV
# ============================================================

agg_df = summary_df.groupby(
    ["experiment_label", "model", "augmentation"],
    as_index=False
)[TARGET_METRICS].agg(["mean", "std", "median"])

agg_df.columns = [
    "_".join(col).strip("_") if isinstance(col, tuple) else col
    for col in agg_df.columns
]

agg_csv_path = os.path.join(
    CSV_OUTPUT_DIR,
    "test_metrics_aggregated_mean_std_median.csv"
)

agg_df.to_csv(agg_csv_path, index=False, encoding="utf-8-sig")

print("\nSaved aggregated table:")
print(agg_csv_path)

display(agg_df.head())


# ============================================================
# 8. CHECK METRIC RANGES
# ============================================================

print("\nMetric ranges used for boxplots:")

for metric in BOXPLOT_METRICS.keys():
    metric_min = summary_df[metric].min()
    metric_max = summary_df[metric].max()
    ylim = BOXPLOT_METRICS[metric]["ylim"]

    print(f"{metric}: min={metric_min:.4f}, max={metric_max:.4f}, ylim={ylim}")


# ============================================================
# 9. CREATE BOXPLOTS SVG
# ============================================================

sns.set_theme(style="whitegrid")


def make_boxplot(data, y_col, y_label, title, output_name, ylim):
    plot_df = data[["experiment_label", y_col]].dropna().copy()

    if plot_df.empty:
        raise ValueError(f"No data available for {y_col}")

    print(f"\nPlotting: {y_col}")
    print("Min:", plot_df[y_col].min())
    print("Max:", plot_df[y_col].max())
    print("Y limit:", ylim)

    plt.figure(figsize=(24, 8))

    ax = sns.boxplot(
        data=plot_df,
        x="experiment_label",
        y=y_col,
        order=EXPERIMENT_ORDER,
        width=0.58,
        showcaps=True,
        showfliers=False,
        boxprops=dict(
            facecolor="#cfe8ff",
            edgecolor="#1f4e79",
            linewidth=1.8
        ),
        whiskerprops=dict(
            color="#1f4e79",
            linewidth=1.8
        ),
        capprops=dict(
            color="#1f4e79",
            linewidth=1.8
        ),
        medianprops=dict(
            color="#08306b",
            linewidth=2.5
        )
    )

    sns.stripplot(
        data=plot_df,
        x="experiment_label",
        y=y_col,
        order=EXPERIMENT_ORDER,
        color="#0b3d91",
        size=4,
        alpha=0.7,
        jitter=0.16,
        ax=ax
    )

    ax.set_xlabel(
        "Model and augmentation setting",
        fontsize=13,
        fontweight="bold"
    )

    ax.set_ylabel(
        y_label,
        fontsize=13,
        fontweight="bold"
    )

    ax.set_title(
        title,
        fontsize=15,
        fontweight="bold",
        pad=14
    )

    ax.set_ylim(ylim[0], ylim[1])

    plt.xticks(rotation=45, ha="right", fontsize=10)
    plt.yticks(fontsize=10)

    ax.grid(axis="y", linestyle="--", alpha=0.25)
    ax.grid(axis="x", visible=False)

    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    plt.tight_layout()

    save_path = os.path.join(PLOTS_OUTPUT_DIR, output_name)

    plt.savefig(save_path, format="svg", bbox_inches="tight", dpi=300)
    plt.show()
    plt.close()

    print(f"Saved boxplot: {save_path}")


for metric, info in BOXPLOT_METRICS.items():
    make_boxplot(
        data=summary_df,
        y_col=metric,
        y_label=info["ylabel"],
        title=info["title"],
        output_name=info["filename"],
        ylim=info["ylim"]
    )


# ============================================================
# 10. FRIEDMAN + WILCOXON HOLM FOR F1 MACRO
# ============================================================

metric_col = "f1_macro"

stats_df = summary_df.dropna(
    subset=["fold", metric_col, "experiment_label"]
).copy()

pivot_df = stats_df.pivot_table(
    index="fold",
    columns="experiment_label",
    values=metric_col,
    aggfunc="mean"
)

available_cols = [
    col for col in EXPERIMENT_ORDER
    if col in pivot_df.columns
]

pivot_df = pivot_df[available_cols]

pivot_df = pivot_df.dropna(axis=0, how="any")

pivot_csv_path = os.path.join(
    CSV_OUTPUT_DIR,
    f"paired_matrix_{metric_col}.csv"
)

pivot_df.to_csv(pivot_csv_path, encoding="utf-8-sig")

print("\nSaved paired matrix:")
print(pivot_csv_path)

display(pivot_df)

if pivot_df.shape[0] < 2:
    raise ValueError("Not enough folds for statistical analysis.")

if pivot_df.shape[1] < 3:
    raise ValueError("At least 3 experiments are required for Friedman test.")


friedman_stat, friedman_p = friedmanchisquare(
    *[pivot_df[col].values for col in pivot_df.columns]
)

ranks_per_fold = pivot_df.apply(
    lambda row: rankdata(-row.values, method="average"),
    axis=1,
    result_type="expand"
)

ranks_per_fold.columns = pivot_df.columns

avg_ranks_df = pd.DataFrame({
    "experiment": ranks_per_fold.columns,
    "average_rank": ranks_per_fold.mean(axis=0).values,
    "mean_metric": pivot_df.mean(axis=0).values,
    "std_metric": pivot_df.std(axis=0, ddof=1).values,
    "median_metric": pivot_df.median(axis=0).values
})

avg_ranks_df = avg_ranks_df.sort_values(
    ["average_rank", "mean_metric"],
    ascending=[True, False]
).reset_index(drop=True)

best_experiment = avg_ranks_df.iloc[0]["experiment"]

friedman_results = pd.DataFrame([{
    "metric": metric_col,
    "best_experiment_selected_by_friedman_rank": best_experiment,
    "n_folds": pivot_df.shape[0],
    "n_experiments": pivot_df.shape[1],
    "friedman_statistic": friedman_stat,
    "friedman_p_value": friedman_p
}])


# ============================================================
# 11. POST HOC WILCOXON + HOLM
# ============================================================

baseline_values = pivot_df[best_experiment].values

posthoc_rows = []

for exp in pivot_df.columns:
    if exp == best_experiment:
        continue

    comparison_values = pivot_df[exp].values

    if np.allclose(baseline_values, comparison_values):
        stat = 0.0
        p_value = 1.0
    else:
        try:
            stat, p_value = wilcoxon(
                baseline_values,
                comparison_values,
                zero_method="wilcox",
                alternative="two-sided",
                mode="auto"
            )
        except ValueError:
            stat = np.nan
            p_value = 1.0

    baseline_mean = np.mean(baseline_values)
    comparison_mean = np.mean(comparison_values)

    posthoc_rows.append({
        "baseline_best_experiment": best_experiment,
        "comparison": exp,
        "baseline_mean": baseline_mean,
        "comparison_mean": comparison_mean,
        "mean_difference": baseline_mean - comparison_mean,
        "wilcoxon_statistic": stat,
        "p_value_raw": p_value
    })

posthoc_df = pd.DataFrame(posthoc_rows)

reject, pvals_corrected, _, _ = multipletests(
    posthoc_df["p_value_raw"].values,
    alpha=0.05,
    method="holm"
)

posthoc_df["p_value_holm"] = pvals_corrected
posthoc_df["reject_h0_holm"] = reject


def interpret(row):
    if row["reject_h0_holm"]:
        if row["mean_difference"] > 0:
            return f"{row['baseline_best_experiment']} significantly better"
        elif row["mean_difference"] < 0:
            return f"{row['comparison']} significantly better"
        else:
            return "significant difference"

    return "no significant difference"


posthoc_df["interpretation"] = posthoc_df.apply(interpret, axis=1)

posthoc_df = posthoc_df.sort_values(
    ["p_value_holm", "p_value_raw", "comparison"]
).reset_index(drop=True)


# ============================================================
# 12. SAVE STATISTICAL CSV TABLES
# ============================================================

friedman_csv_path = os.path.join(
    CSV_OUTPUT_DIR,
    f"friedman_{metric_col}.csv"
)

ranks_csv_path = os.path.join(
    CSV_OUTPUT_DIR,
    f"friedman_average_ranks_{metric_col}.csv"
)

posthoc_csv_path = os.path.join(
    CSV_OUTPUT_DIR,
    f"posthoc_wilcoxon_holm_{metric_col}.csv"
)

friedman_results.to_csv(
    friedman_csv_path,
    index=False,
    encoding="utf-8-sig"
)

avg_ranks_df.to_csv(
    ranks_csv_path,
    index=False,
    encoding="utf-8-sig"
)

posthoc_df.to_csv(
    posthoc_csv_path,
    index=False,
    encoding="utf-8-sig"
)

print("\nSaved statistical CSV tables:")
print(friedman_csv_path)
print(ranks_csv_path)
print(posthoc_csv_path)

print("\nBest experiment by Friedman average rank:")
print(best_experiment)

print("\nFriedman results:")
display(friedman_results)

print("\nAverage ranks:")
display(avg_ranks_df)

print("\nPost hoc Wilcoxon + Holm:")
display(posthoc_df)

print("\nDONE.")
print("Final output folder:", FINAL_OUTPUT_DIR)
print("CSV tables folder:", CSV_OUTPUT_DIR)
print("Boxplots SVG folder:", PLOTS_OUTPUT_DIR)

# ============================================================
# 1. CONFIGURATION
# ============================================================

RESULTS_ROOT = ".../Paper/results 1/results/Features"

FINAL_OUTPUT_DIR = ".../Paper/results 1/results/Resultado_final_Features"

CSV_OUTPUT_DIR = os.path.join(FINAL_OUTPUT_DIR, "csv_tables")
PLOTS_OUTPUT_DIR = os.path.join(FINAL_OUTPUT_DIR, "boxplots_svg")

os.makedirs(FINAL_OUTPUT_DIR, exist_ok=True)
os.makedirs(CSV_OUTPUT_DIR, exist_ok=True)
os.makedirs(PLOTS_OUTPUT_DIR, exist_ok=True)


MODEL_MAP = {
    "logreg": "Logistic Regression",
    "rf": "Random Forest",
    "svm": "Support Vector Machine",
    "mlp": "MLP"
}

LABEL_MAP = {
    "Logistic Regression": "LogReg",
    "Random Forest": "RF",
    "Support Vector Machine": "SVM",
    "MLP": "MLP",
    "logreg": "LogReg",
    "rf": "RF",
    "svm": "SVM",
    "mlp": "MLP"
}

MODEL_ORDER = ["logreg", "rf", "svm", "mlp"]

VALID_AUGMENTATIONS = ["noaug", "100", "500", "1000", "2000", "4000"]

EXPERIMENT_ORDER = [
    "LogReg", "LogReg +100", "LogReg +500", "LogReg +1000", "LogReg +2000", "LogReg +4000",
    "RF", "RF +100", "RF +500", "RF +1000", "RF +2000", "RF +4000",
    "SVM", "SVM +100", "SVM +500", "SVM +1000", "SVM +2000", "SVM +4000",
    "MLP", "MLP +100", "MLP +500", "MLP +1000", "MLP +2000", "MLP +4000"
]

TARGET_METRICS = [
    "accuracy",
    "precision_weighted",
    "recall_weighted",
    "f1_weighted",
    "precision_macro",
    "recall_macro",
    "f1_macro",
    "balanced_accuracy",
    "roc_auc_macro_ovr"
]


# ============================================================
# 2. BOXPLOT SETTINGS
# ============================================================

BOXPLOT_METRICS = {
    "roc_auc_macro_ovr": {
        "ylabel": "Macro AUC OVR per fold",
        "title": "Test Macro AUC by Model and Augmentation",
        "filename": "test_macro_auc_boxplot_0_4_1_0.svg",
        "ylim": (0.4, 1.0)
    },
    "f1_macro": {
        "ylabel": "Macro F1 score per fold",
        "title": "Test Macro F1 Score by Model and Augmentation",
        "filename": "test_f1_macro_boxplot_0_4_0_7.svg",
        "ylim": (0.4, 1)
    },
    "f1_weighted": {
        "ylabel": "Weighted F1 score per fold",
        "title": "Test Weighted F1 Score by Model and Augmentation",
        "filename": "test_f1_weighted_boxplot_0_4_1_0.svg",
        "ylim": (0.4, 1.0)
    },
    "balanced_accuracy": {
        "ylabel": "Balanced accuracy per fold",
        "title": "Test Balanced Accuracy by Model and Augmentation",
        "filename": "test_balanced_accuracy_boxplot_0_4_0_7.svg",
        "ylim": (0.4, 1)
    }
}


# ============================================================
# 3. HELPER FUNCTIONS
# ============================================================

def parse_augmentation(folder_name):
    m = re.match(r"cv_benchmark_results_(.+?)_cv$", folder_name.lower())
    return m.group(1) if m else None


def make_experiment_label(model, augmentation):
    short_model = LABEL_MAP.get(str(model).strip(), str(model).strip())
    aug = str(augmentation).strip().lower()

    if aug == "noaug":
        return short_model

    return f"{short_model} +{aug}"


def find_metrics_summary_file(fold_dir):
    for fname in os.listdir(fold_dir):
        low = fname.lower()

        if low == "metrics_summary" or low == "metrics_summary.csv":
            return os.path.join(fold_dir, fname)

    for fname in os.listdir(fold_dir):
        if "metrics_summary" in fname.lower():
            return os.path.join(fold_dir, fname)

    return None


def read_metrics_summary(file_path):
    try:
        df = pd.read_csv(file_path)
    except Exception:
        df = pd.read_csv(file_path, sep=None, engine="python")

    df.columns = [str(c).strip().lower() for c in df.columns]

    if "split" not in df.columns:
        raise ValueError(f"No existe columna 'split' en {file_path}")

    df["split"] = df["split"].astype(str).str.strip().str.lower()

    test_row = df[df["split"] == "test"]

    if test_row.empty:
        raise ValueError(f"No se encontró fila 'Test' en {file_path}")

    test_row = test_row.iloc[0]

    result = {}

    for metric in TARGET_METRICS:
        result[metric] = pd.to_numeric(test_row.get(metric, None), errors="coerce")

    return result


# ============================================================
# 4. EXTRACT TEST METRICS FROM ALL FOLDS
# ============================================================

rows = []

for folder_name in sorted(os.listdir(RESULTS_ROOT)):
    folder_path = os.path.join(RESULTS_ROOT, folder_name)

    if not os.path.isdir(folder_path):
        continue

    augmentation = parse_augmentation(folder_name)

    if augmentation is None:
        continue

    augmentation = str(augmentation).strip().lower()

    if augmentation not in VALID_AUGMENTATIONS:
        continue

    for model_key in MODEL_ORDER:
        model_dir = os.path.join(folder_path, model_key)

        if not os.path.isdir(model_dir):
            print(f"[WARNING] Model folder not found: {model_dir}")
            continue

        for subfolder in sorted(os.listdir(model_dir)):
            fold_dir = os.path.join(model_dir, subfolder)

            if not os.path.isdir(fold_dir):
                continue

            if not re.match(r"cv_fold_test_img_\d+$", subfolder.lower()):
                continue

            fold_match = re.search(r"(\d+)$", subfolder)
            fold_id = int(fold_match.group(1)) if fold_match else None

            metrics_file = find_metrics_summary_file(fold_dir)

            if metrics_file is None:
                print(f"[WARNING] metrics_summary not found in: {fold_dir}")
                continue

            try:
                metrics = read_metrics_summary(metrics_file)

                row = {
                    "source_folder": folder_name,
                    "model_key": model_key,
                    "model": MODEL_MAP[model_key],
                    "augmentation": augmentation,
                    "fold": fold_id,
                    "split": "Test",
                    "metrics_file": metrics_file
                }

                row.update(metrics)
                rows.append(row)

                print(f"[OK] {folder_name} | {model_key} | fold {fold_id}")

            except Exception as e:
                print(f"[ERROR] {metrics_file}: {e}")


summary_df = pd.DataFrame(rows)

if summary_df.empty:
    raise ValueError("No data extracted. Check folders and metrics_summary files.")


# ============================================================
# 5. CLEAN DATA
# ============================================================

summary_df["model"] = summary_df["model"].astype(str).str.strip()
summary_df["augmentation"] = summary_df["augmentation"].astype(str).str.strip().str.lower()
summary_df["fold"] = pd.to_numeric(summary_df["fold"], errors="coerce")

summary_df["experiment_label"] = [
    make_experiment_label(m, a)
    for m, a in zip(summary_df["model"], summary_df["augmentation"])
]

summary_df = summary_df[summary_df["experiment_label"].isin(EXPERIMENT_ORDER)].copy()

for col in TARGET_METRICS:
    summary_df[col] = pd.to_numeric(summary_df[col], errors="coerce")

summary_df = summary_df.sort_values(
    ["model_key", "augmentation", "fold"]
).reset_index(drop=True)


# ============================================================
# 6. SAVE FULL FOLD-LEVEL CSV
# ============================================================

full_csv_path = os.path.join(
    CSV_OUTPUT_DIR,
    "test_metrics_by_fold_all_experiments.csv"
)

summary_df.to_csv(full_csv_path, index=False, encoding="utf-8-sig")

print("\nSaved full fold-level table:")
print(full_csv_path)

display(summary_df.head())


# ============================================================
# 7. SAVE AGGREGATED SUMMARY CSV
# ============================================================

agg_df = summary_df.groupby(
    ["experiment_label", "model", "augmentation"],
    as_index=False
)[TARGET_METRICS].agg(["mean", "std", "median"])

agg_df.columns = [
    "_".join(col).strip("_") if isinstance(col, tuple) else col
    for col in agg_df.columns
]

agg_csv_path = os.path.join(
    CSV_OUTPUT_DIR,
    "test_metrics_aggregated_mean_std_median.csv"
)

agg_df.to_csv(agg_csv_path, index=False, encoding="utf-8-sig")

print("\nSaved aggregated table:")
print(agg_csv_path)

display(agg_df.head())


# ============================================================
# 8. CHECK METRIC RANGES
# ============================================================

print("\nMetric ranges used for boxplots:")

for metric in BOXPLOT_METRICS.keys():
    metric_min = summary_df[metric].min()
    metric_max = summary_df[metric].max()
    ylim = BOXPLOT_METRICS[metric]["ylim"]

    print(f"{metric}: min={metric_min:.4f}, max={metric_max:.4f}, ylim={ylim}")


# ============================================================
# 9. CREATE BOXPLOTS SVG
# ============================================================

sns.set_theme(style="whitegrid")


def make_boxplot(data, y_col, y_label, title, output_name, ylim):
    plot_df = data[["experiment_label", y_col]].dropna().copy()

    if plot_df.empty:
        raise ValueError(f"No data available for {y_col}")

    print(f"\nPlotting: {y_col}")
    print("Min:", plot_df[y_col].min())
    print("Max:", plot_df[y_col].max())
    print("Y limit:", ylim)

    plt.figure(figsize=(24, 8))

    ax = sns.boxplot(
        data=plot_df,
        x="experiment_label",
        y=y_col,
        order=EXPERIMENT_ORDER,
        width=0.58,
        showcaps=True,
        showfliers=False,
        boxprops=dict(
            facecolor="#cfe8ff",
            edgecolor="#1f4e79",
            linewidth=1.8
        ),
        whiskerprops=dict(
            color="#1f4e79",
            linewidth=1.8
        ),
        capprops=dict(
            color="#1f4e79",
            linewidth=1.8
        ),
        medianprops=dict(
            color="#08306b",
            linewidth=2.5
        )
    )

    sns.stripplot(
        data=plot_df,
        x="experiment_label",
        y=y_col,
        order=EXPERIMENT_ORDER,
        color="#0b3d91",
        size=4,
        alpha=0.7,
        jitter=0.16,
        ax=ax
    )

    ax.set_xlabel(
        "Model and augmentation setting",
        fontsize=13,
        fontweight="bold"
    )

    ax.set_ylabel(
        y_label,
        fontsize=13,
        fontweight="bold"
    )

    ax.set_title(
        title,
        fontsize=15,
        fontweight="bold",
        pad=14
    )

    ax.set_ylim(ylim[0], ylim[1])

    plt.xticks(rotation=45, ha="right", fontsize=10)
    plt.yticks(fontsize=10)

    ax.grid(axis="y", linestyle="--", alpha=0.25)
    ax.grid(axis="x", visible=False)

    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    plt.tight_layout()

    save_path = os.path.join(PLOTS_OUTPUT_DIR, output_name)

    plt.savefig(save_path, format="svg", bbox_inches="tight", dpi=300)
    plt.show()
    plt.close()

    print(f"Saved boxplot: {save_path}")


for metric, info in BOXPLOT_METRICS.items():
    make_boxplot(
        data=summary_df,
        y_col=metric,
        y_label=info["ylabel"],
        title=info["title"],
        output_name=info["filename"],
        ylim=info["ylim"]
    )


# ============================================================
# 10. FRIEDMAN + WILCOXON HOLM FOR F1 MACRO
# ============================================================

metric_col = "f1_macro"

stats_df = summary_df.dropna(
    subset=["fold", metric_col, "experiment_label"]
).copy()

pivot_df = stats_df.pivot_table(
    index="fold",
    columns="experiment_label",
    values=metric_col,
    aggfunc="mean"
)

available_cols = [
    col for col in EXPERIMENT_ORDER
    if col in pivot_df.columns
]

pivot_df = pivot_df[available_cols]

pivot_df = pivot_df.dropna(axis=0, how="any")

pivot_csv_path = os.path.join(
    CSV_OUTPUT_DIR,
    f"paired_matrix_{metric_col}.csv"
)

pivot_df.to_csv(pivot_csv_path, encoding="utf-8-sig")

print("\nSaved paired matrix:")
print(pivot_csv_path)

display(pivot_df)

if pivot_df.shape[0] < 2:
    raise ValueError("Not enough folds for statistical analysis.")

if pivot_df.shape[1] < 3:
    raise ValueError("At least 3 experiments are required for Friedman test.")


friedman_stat, friedman_p = friedmanchisquare(
    *[pivot_df[col].values for col in pivot_df.columns]
)

ranks_per_fold = pivot_df.apply(
    lambda row: rankdata(-row.values, method="average"),
    axis=1,
    result_type="expand"
)

ranks_per_fold.columns = pivot_df.columns

avg_ranks_df = pd.DataFrame({
    "experiment": ranks_per_fold.columns,
    "average_rank": ranks_per_fold.mean(axis=0).values,
    "mean_metric": pivot_df.mean(axis=0).values,
    "std_metric": pivot_df.std(axis=0, ddof=1).values,
    "median_metric": pivot_df.median(axis=0).values
})

avg_ranks_df = avg_ranks_df.sort_values(
    ["average_rank", "mean_metric"],
    ascending=[True, False]
).reset_index(drop=True)

best_experiment = avg_ranks_df.iloc[0]["experiment"]

friedman_results = pd.DataFrame([{
    "metric": metric_col,
    "best_experiment_selected_by_friedman_rank": best_experiment,
    "n_folds": pivot_df.shape[0],
    "n_experiments": pivot_df.shape[1],
    "friedman_statistic": friedman_stat,
    "friedman_p_value": friedman_p
}])


# ============================================================
# 11. POST HOC WILCOXON + HOLM
# ============================================================

baseline_values = pivot_df[best_experiment].values

posthoc_rows = []

for exp in pivot_df.columns:
    if exp == best_experiment:
        continue

    comparison_values = pivot_df[exp].values

    if np.allclose(baseline_values, comparison_values):
        stat = 0.0
        p_value = 1.0
    else:
        try:
            stat, p_value = wilcoxon(
                baseline_values,
                comparison_values,
                zero_method="wilcox",
                alternative="two-sided",
                mode="auto"
            )
        except ValueError:
            stat = np.nan
            p_value = 1.0

    baseline_mean = np.mean(baseline_values)
    comparison_mean = np.mean(comparison_values)

    posthoc_rows.append({
        "baseline_best_experiment": best_experiment,
        "comparison": exp,
        "baseline_mean": baseline_mean,
        "comparison_mean": comparison_mean,
        "mean_difference": baseline_mean - comparison_mean,
        "wilcoxon_statistic": stat,
        "p_value_raw": p_value
    })

posthoc_df = pd.DataFrame(posthoc_rows)

reject, pvals_corrected, _, _ = multipletests(
    posthoc_df["p_value_raw"].values,
    alpha=0.05,
    method="holm"
)

posthoc_df["p_value_holm"] = pvals_corrected
posthoc_df["reject_h0_holm"] = reject


def interpret(row):
    if row["reject_h0_holm"]:
        if row["mean_difference"] > 0:
            return f"{row['baseline_best_experiment']} significantly better"
        elif row["mean_difference"] < 0:
            return f"{row['comparison']} significantly better"
        else:
            return "significant difference"

    return "no significant difference"


posthoc_df["interpretation"] = posthoc_df.apply(interpret, axis=1)

posthoc_df = posthoc_df.sort_values(
    ["p_value_holm", "p_value_raw", "comparison"]
).reset_index(drop=True)


# ============================================================
# 12. SAVE STATISTICAL CSV TABLES
# ============================================================

friedman_csv_path = os.path.join(
    CSV_OUTPUT_DIR,
    f"friedman_{metric_col}.csv"
)

ranks_csv_path = os.path.join(
    CSV_OUTPUT_DIR,
    f"friedman_average_ranks_{metric_col}.csv"
)

posthoc_csv_path = os.path.join(
    CSV_OUTPUT_DIR,
    f"posthoc_wilcoxon_holm_{metric_col}.csv"
)

friedman_results.to_csv(
    friedman_csv_path,
    index=False,
    encoding="utf-8-sig"
)

avg_ranks_df.to_csv(
    ranks_csv_path,
    index=False,
    encoding="utf-8-sig"
)

posthoc_df.to_csv(
    posthoc_csv_path,
    index=False,
    encoding="utf-8-sig"
)

print("\nSaved statistical CSV tables:")
print(friedman_csv_path)
print(ranks_csv_path)
print(posthoc_csv_path)

print("\nBest experiment by Friedman average rank:")
print(best_experiment)

print("\nFriedman results:")
display(friedman_results)

print("\nAverage ranks:")
display(avg_ranks_df)

print("\nPost hoc Wilcoxon + Holm:")
display(posthoc_df)

print("\nDONE.")
print("Final output folder:", FINAL_OUTPUT_DIR)
print("CSV tables folder:", CSV_OUTPUT_DIR)
print("Boxplots SVG folder:", PLOTS_OUTPUT_DIR)

import json


# ============================================================
# 1. CONFIGURATION
# ============================================================

RESULTS_ROOT = ".../Paper/results 1/results/direct_patch_classification/resnet3d_18"

FINAL_OUTPUT_DIR = ".../Paper/results 1/results/Resultado_final_resnet"

CSV_OUTPUT_DIR = os.path.join(FINAL_OUTPUT_DIR, "csv_tables")
PLOTS_OUTPUT_DIR = os.path.join(FINAL_OUTPUT_DIR, "boxplots_svg")

os.makedirs(FINAL_OUTPUT_DIR, exist_ok=True)
os.makedirs(CSV_OUTPUT_DIR, exist_ok=True)
os.makedirs(PLOTS_OUTPUT_DIR, exist_ok=True)


MODEL_KEY = "resnet3d_18"
MODEL_NAME = "ResNet3D-18"
EXPERIMENT_LABEL = "ResNet3D-18"


# ============================================================
# 2. METRICS TO EXTRACT
# ============================================================

TARGET_METRICS = [
    "accuracy",
    "precision_weighted",
    "recall_weighted",
    "f1_weighted",
    "precision_macro",
    "recall_macro",
    "f1_macro",
    "balanced_accuracy"
]


# ============================================================
# 3. BOXPLOT SETTINGS
# ============================================================

BOXPLOT_METRICS = {
    "f1_macro": {
        "ylabel": "Macro F1 score per fold",
        "title": "Test Macro F1 Score - ResNet3D-18",
        "filename": "resnet3d_18_f1_macro_boxplot_0_4_0_7.svg",
        "ylim": (0.4, 1)
    },
    "f1_weighted": {
        "ylabel": "Weighted F1 score per fold",
        "title": "Test Weighted F1 Score - ResNet3D-18",
        "filename": "resnet3d_18_f1_weighted_boxplot_0_4_1_0.svg",
        "ylim": (0.4, 1.0)
    },
    "balanced_accuracy": {
        "ylabel": "Balanced accuracy per fold",
        "title": "Test Balanced Accuracy - ResNet3D-18",
        "filename": "resnet3d_18_balanced_accuracy_boxplot_0_4_0_7.svg",
        "ylim": (0.4, 1)
    }
}


# ============================================================
# 4. HELPER FUNCTIONS
# ============================================================

def normalize_text(x):
    x = str(x).strip().lower()
    x = x.replace("-", "_")
    x = x.replace(" ", "_")
    return x


def flatten_json(d, parent_key="", sep="_"):
    items = {}

    if isinstance(d, dict):
        for k, v in d.items():
            new_key = f"{parent_key}{sep}{k}" if parent_key else str(k)
            items.update(flatten_json(v, new_key, sep=sep))

    elif isinstance(d, list):
        for i, v in enumerate(d):
            new_key = f"{parent_key}{sep}{i}" if parent_key else str(i)
            items.update(flatten_json(v, new_key, sep=sep))

    else:
        items[parent_key] = d

    return items


def find_metric_value(flat_data, metric_name):
    metric_norm = normalize_text(metric_name)

    normalized_data = {
        normalize_text(k): v
        for k, v in flat_data.items()
    }

    possible_names = [
        f"test_{metric_norm}",
        f"test_metrics_{metric_norm}",
        f"metrics_test_{metric_norm}",
        f"summary_test_{metric_norm}",
        metric_norm,
        f"metrics_{metric_norm}",
        f"summary_{metric_norm}"
    ]

    for name in possible_names:
        if name in normalized_data:
            return normalized_data[name]

    for k, v in normalized_data.items():
        if k.endswith(f"test_{metric_norm}"):
            return v

    for k, v in normalized_data.items():
        if k.endswith(metric_norm):
            return v

    return None


# ============================================================
# 5. EXTRACT METRICS FROM fold_summary.json FILES
# ============================================================

rows = []

for folder_name in sorted(os.listdir(RESULTS_ROOT)):
    folder_path = os.path.join(RESULTS_ROOT, folder_name)

    if not os.path.isdir(folder_path):
        continue

    if not re.match(r"img_\d+$", folder_name.lower()):
        continue

    fold_match = re.search(r"(\d+)$", folder_name)
    fold_id = int(fold_match.group(1)) if fold_match else None

    json_path = os.path.join(folder_path, "fold_summary.json")

    if not os.path.exists(json_path):
        print(f"[WARNING] fold_summary.json not found in: {folder_path}")
        continue

    try:
        with open(json_path, "r", encoding="utf-8") as f:
            data = json.load(f)

        flat_data = flatten_json(data)

        row = {
            "source_folder": folder_name,
            "model_key": MODEL_KEY,
            "model": MODEL_NAME,
            "experiment_label": EXPERIMENT_LABEL,
            "augmentation": "direct_patch",
            "fold": fold_id,
            "split": "Test",
            "metrics_file": json_path
        }

        for metric in TARGET_METRICS:
            row[metric] = find_metric_value(flat_data, metric)

        rows.append(row)

        print(f"[OK] {folder_name} | fold {fold_id}")

    except Exception as e:
        print(f"[ERROR] {json_path}: {e}")


summary_df = pd.DataFrame(rows)

if summary_df.empty:
    raise ValueError("No data extracted. Check the folder path or JSON structure.")


# ============================================================
# 6. CLEAN DATA
# ============================================================

summary_df["fold"] = pd.to_numeric(summary_df["fold"], errors="coerce")

for col in TARGET_METRICS:
    summary_df[col] = pd.to_numeric(summary_df[col], errors="coerce")

summary_df = summary_df.sort_values("fold").reset_index(drop=True)

print("\nExtracted table:")
display(summary_df)


# ============================================================
# 7. SAVE FULL FOLD-LEVEL CSV
# ============================================================

full_csv_path = os.path.join(
    CSV_OUTPUT_DIR,
    "resnet3d_18_test_metrics_by_fold.csv"
)

summary_df.to_csv(full_csv_path, index=False, encoding="utf-8-sig")

print("\nSaved full fold-level CSV:")
print(full_csv_path)


# ============================================================
# 8. SAVE AGGREGATED SUMMARY CSV
# ============================================================

agg_df = summary_df.groupby(
    ["experiment_label", "model", "augmentation"],
    as_index=False
)[TARGET_METRICS].agg(["mean", "std", "median", "min", "max"])

agg_df.columns = [
    "_".join(col).strip("_") if isinstance(col, tuple) else col
    for col in agg_df.columns
]

agg_csv_path = os.path.join(
    CSV_OUTPUT_DIR,
    "resnet3d_18_test_metrics_aggregated_mean_std_median_min_max.csv"
)

agg_df.to_csv(agg_csv_path, index=False, encoding="utf-8-sig")

print("\nSaved aggregated CSV:")
print(agg_csv_path)

display(agg_df)


# ============================================================
# 9. SAVE MISSING VALUES TABLE
# ============================================================

missing_summary = summary_df[TARGET_METRICS].isna().sum().reset_index()
missing_summary.columns = ["metric", "missing_values"]

missing_csv_path = os.path.join(
    CSV_OUTPUT_DIR,
    "resnet3d_18_missing_values_by_metric.csv"
)

missing_summary.to_csv(missing_csv_path, index=False, encoding="utf-8-sig")

print("\nSaved missing-values CSV:")
print(missing_csv_path)

display(missing_summary)


# ============================================================
# 10. CHECK METRIC RANGES
# ============================================================

print("\nMetric ranges used for boxplots:")

for metric in BOXPLOT_METRICS.keys():
    metric_min = summary_df[metric].min()
    metric_max = summary_df[metric].max()
    ylim = BOXPLOT_METRICS[metric]["ylim"]

    print(f"{metric}: min={metric_min}, max={metric_max}, ylim={ylim}")


# ============================================================
# 11. CREATE BOXPLOTS SVG
# ============================================================

sns.set_theme(style="whitegrid")


def make_boxplot(data, y_col, y_label, title, output_name, ylim):
    plot_df = data[["experiment_label", y_col]].dropna().copy()

    if plot_df.empty:
        print(f"[WARNING] No data available for {y_col}. Skipping this boxplot.")
        return

    print(f"\nPlotting: {y_col}")
    print("N:", len(plot_df))
    print("Min:", plot_df[y_col].min())
    print("Max:", plot_df[y_col].max())
    print("Y limit:", ylim)

    plt.figure(figsize=(7, 7))

    ax = sns.boxplot(
        data=plot_df,
        x="experiment_label",
        y=y_col,
        order=[EXPERIMENT_LABEL],
        width=0.45,
        showcaps=True,
        showfliers=False,
        boxprops=dict(
            facecolor="#cfe8ff",
            edgecolor="#1f4e79",
            linewidth=1.8
        ),
        whiskerprops=dict(
            color="#1f4e79",
            linewidth=1.8
        ),
        capprops=dict(
            color="#1f4e79",
            linewidth=1.8
        ),
        medianprops=dict(
            color="#08306b",
            linewidth=2.5
        )
    )

    sns.stripplot(
        data=plot_df,
        x="experiment_label",
        y=y_col,
        order=[EXPERIMENT_LABEL],
        color="#0b3d91",
        size=6,
        alpha=0.75,
        jitter=0.10,
        ax=ax
    )

    ax.set_xlabel("Model", fontsize=13, fontweight="bold")
    ax.set_ylabel(y_label, fontsize=13, fontweight="bold")
    ax.set_title(title, fontsize=15, fontweight="bold", pad=14)

    ax.set_ylim(ylim[0], ylim[1])

    plt.xticks(rotation=0, fontsize=11)
    plt.yticks(fontsize=10)

    ax.grid(axis="y", linestyle="--", alpha=0.25)
    ax.grid(axis="x", visible=False)

    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    plt.tight_layout()

    save_path = os.path.join(PLOTS_OUTPUT_DIR, output_name)

    plt.savefig(save_path, format="svg", bbox_inches="tight", dpi=300)
    plt.show()
    plt.close()

    print(f"Saved SVG boxplot: {save_path}")


for metric, info in BOXPLOT_METRICS.items():
    make_boxplot(
        data=summary_df,
        y_col=metric,
        y_label=info["ylabel"],
        title=info["title"],
        output_name=info["filename"],
        ylim=info["ylim"]
    )


# ============================================================
# 12. FINAL MESSAGE
# ============================================================

print("\nDONE.")
print("Final output folder:", FINAL_OUTPUT_DIR)
print("CSV tables folder:", CSV_OUTPUT_DIR)
print("Boxplots SVG folder:", PLOTS_OUTPUT_DIR)

import os
import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from scipy.stats import friedmanchisquare, wilcoxon, rankdata
from statsmodels.stats.multitest import multipletests
from IPython.display import display


# ============================================================
# 1. PATHS
# ============================================================

BASE_RESULTS_DIR = ".../Paper/results 1/results"

DINO_DIR = os.path.join(BASE_RESULTS_DIR, "Resultado_final_DINO3D")
RESNET_DIR = os.path.join(BASE_RESULTS_DIR, "Resultado_final_resnet")
FEATURES_DIR = os.path.join(BASE_RESULTS_DIR, "Resultado_final_Features")

OUTPUT_DIR = os.path.join(BASE_RESULTS_DIR, "Resultado_final_modelos")
CSV_OUTPUT_DIR = os.path.join(OUTPUT_DIR, "csv_tables")
PLOT_OUTPUT_DIR = os.path.join(OUTPUT_DIR, "plots_svg")

os.makedirs(OUTPUT_DIR, exist_ok=True)
os.makedirs(CSV_OUTPUT_DIR, exist_ok=True)
os.makedirs(PLOT_OUTPUT_DIR, exist_ok=True)


# ============================================================
# 2. INPUT CSV FILES
# ============================================================

DINO_CSV = os.path.join(
    DINO_DIR,
    "csv_tables",
    "test_metrics_by_fold_all_experiments.csv"
)

RESNET_CSV = os.path.join(
    RESNET_DIR,
    "csv_tables",
    "resnet3d_18_test_metrics_by_fold.csv"
)

FEATURES_CSV = os.path.join(
    FEATURES_DIR,
    "csv_tables",
    "test_metrics_by_fold_all_experiments.csv"
)


# ============================================================
# 3. GENERAL SETTINGS
# ============================================================

METRIC_COLS = [
    "f1_macro",
    "f1_weighted",
    "balanced_accuracy"
]

MAIN_METRIC = "f1_macro"

METRIC_LABELS = {
    "f1_macro": "Macro F1 score per fold",
    "f1_weighted": "Weighted F1 score per fold",
    "balanced_accuracy": "Balanced accuracy per fold"
}

ORDER_MODE = "manual"

Y_AXIS_MIN = 0.4
Y_AXIS_MAX = 1.0

BRACKET_HEIGHT = 0.012
BRACKET_START_GAP = 0.025
BRACKET_LEVEL_GAP = 0.055
BRACKET_TEXT_OFFSET = 0.004

PLOT_WIDTH = 11
PLOT_HEIGHT = 7.5


# ============================================================
# 4. HELPER FUNCTIONS
# ============================================================

def check_file_exists(path, label):
    if not os.path.exists(path):
        raise FileNotFoundError(f"{label} file not found: {path}")
    return path


def normalize_model(model, model_key=None):
    raw = str(model_key if model_key is not None else model).strip().lower()
    raw_model = str(model).strip().lower()

    if raw in ["rf", "random_forest", "random forest"] or "random forest" in raw_model:
        return "RF"

    if raw in ["svm", "support_vector_machine", "support vector machine"] or "svm" in raw_model:
        return "SVM"

    if raw in ["logreg", "logistic regression", "logistic_regression"] or "logistic" in raw_model:
        return "LogReg"

    if raw in ["mlp"] or "mlp" in raw_model:
        return "MLP"

    if "resnet" in raw or "resnet" in raw_model:
        return "ResNet3D-18"

    return str(model).strip()


def normalize_augmentation(augmentation):
    aug = str(augmentation).strip().lower()

    if aug in ["noaug", "no_aug", "none", "nan", "0"]:
        return "noaug"

    for n in ["4000", "2000", "1000", "500", "100"]:
        if n in aug:
            return n

    return aug


def compact_experiment_label(label):
    label = str(label).strip()
    label = re.sub(r"\s*\+\s*", "+", label)
    return label


def create_experiment_label(row):
    if "experiment_label" in row.index and pd.notna(row["experiment_label"]):
        return compact_experiment_label(row["experiment_label"])

    model_short = normalize_model(
        row.get("model", ""),
        row.get("model_key", "")
    )

    aug = normalize_augmentation(row.get("augmentation", "noaug"))

    if aug == "noaug":
        return model_short

    return compact_experiment_label(f"{model_short}+{aug}")


def load_family_data(csv_path, family_name):
    df = pd.read_csv(csv_path)

    if "fold" not in df.columns:
        raise ValueError(f"The file does not contain a 'fold' column: {csv_path}")

    df["fold"] = pd.to_numeric(df["fold"], errors="coerce")

    for col in METRIC_COLS:
        if col not in df.columns:
            raise ValueError(f"The file does not contain metric '{col}': {csv_path}")
        df[col] = pd.to_numeric(df[col], errors="coerce")

    if family_name == "ResNet3D-18":
        df["raw_experiment_label"] = "ResNet3D-18"
    else:
        df["raw_experiment_label"] = df.apply(create_experiment_label, axis=1)

    df["family"] = family_name

    return df


def select_best_experiment(df, family_name, metric_col):
    ranking_df = (
        df.groupby("raw_experiment_label")[metric_col]
        .agg(["mean", "std", "median", "count"])
        .reset_index()
    )

    ranking_df = ranking_df.sort_values(
        ["mean", "median"],
        ascending=[False, False]
    ).reset_index(drop=True)

    best_experiment = ranking_df.iloc[0]["raw_experiment_label"]

    selected_df = df[df["raw_experiment_label"] == best_experiment].copy()
    ranking_df["family"] = family_name

    return selected_df, ranking_df, best_experiment


def build_display_label(family_name, best_experiment):
    if family_name == "ResNet3D-18":
        return "ResNet3D-18"

    best_experiment = compact_experiment_label(best_experiment)

    return f"{family_name}\n{best_experiment}"


def paired_cohens_d(x, y):
    diff = x - y
    mean_diff = np.mean(diff)
    std_diff = np.std(diff, ddof=1)

    if std_diff == 0:
        return np.nan, mean_diff, std_diff

    d = mean_diff / std_diff
    return d, mean_diff, std_diff


def interpret_cohens_d(d):
    if pd.isna(d):
        return "undefined"

    abs_d = abs(d)

    if abs_d < 0.2:
        return "negligible"
    elif abs_d < 0.5:
        return "small"
    elif abs_d < 0.8:
        return "medium"
    else:
        return "large"


def add_bracket(ax, x1, x2, y, h, text):
    ax.plot(
        [x1, x1, x2, x2],
        [y, y + h, y + h, y],
        linewidth=1.5,
        color="black"
    )

    ax.text(
        (x1 + x2) / 2,
        y + h + BRACKET_TEXT_OFFSET,
        text,
        ha="center",
        va="bottom",
        fontsize=9,
        fontweight="bold"
    )


def build_paired_matrix(data, metric_col, order):
    pivot_df = data.pivot_table(
        index="fold",
        columns="display_label",
        values=metric_col,
        aggfunc="mean"
    )

    available_order = [
        item for item in order
        if item in pivot_df.columns
    ]

    pivot_df = pivot_df[available_order]
    pivot_df = pivot_df.dropna(axis=0, how="any")

    return pivot_df


def get_display_order(data, metric_col, manual_order):
    if ORDER_MODE == "manual":
        return manual_order

    mean_scores = (
        data.groupby("display_label")[metric_col]
        .mean()
        .sort_values(ascending=False)
    )

    return mean_scores.index.tolist()


def compute_pairwise_effects(pivot_df, metric_col, display_order):
    effect_rows = []

    for i in range(len(display_order)):
        for j in range(i + 1, len(display_order)):
            left_model = display_order[i]
            right_model = display_order[j]

            if left_model not in pivot_df.columns or right_model not in pivot_df.columns:
                continue

            left_values = pivot_df[left_model].values
            right_values = pivot_df[right_model].values

            d, mean_diff, std_diff = paired_cohens_d(left_values, right_values)

            try:
                stat, p_value = wilcoxon(
                    left_values,
                    right_values,
                    zero_method="wilcox",
                    alternative="two-sided",
                    mode="auto"
                )
            except Exception:
                stat = np.nan
                p_value = np.nan

            effect_rows.append({
                "metric": metric_col,
                "left_model": left_model,
                "right_model": right_model,
                "left_mean": np.mean(left_values),
                "right_mean": np.mean(right_values),
                "mean_difference_left_minus_right": mean_diff,
                "std_difference": std_diff,
                "cohens_d_paired": d,
                "effect_size_interpretation": interpret_cohens_d(d),
                "wilcoxon_statistic": stat,
                "wilcoxon_p_value": p_value
            })

    return pd.DataFrame(effect_rows)


def compute_bracket_layout(effect_df, display_order, top_value):
    x_positions = {
        label: idx
        for idx, label in enumerate(display_order)
    }

    pair_info = []

    for _, row in effect_df.iterrows():
        left_model = row["left_model"]
        right_model = row["right_model"]

        if left_model not in x_positions or right_model not in x_positions:
            continue

        x1 = x_positions[left_model]
        x2 = x_positions[right_model]

        if x1 > x2:
            x1, x2 = x2, x1
            left_model, right_model = right_model, left_model

        d_value = row["cohens_d_paired"]
        interpretation = row["effect_size_interpretation"]

        if pd.isna(d_value):
            label = "d = NaN"
        else:
            label = f"d = {d_value:.2f} ({interpretation})"

        pair_info.append({
            "left_model": left_model,
            "right_model": right_model,
            "x1": x1,
            "x2": x2,
            "span": x2 - x1,
            "label": label
        })

    pair_info = sorted(pair_info, key=lambda item: (item["span"], item["x1"]))

    levels = []
    placed_pairs = []

    for pair in pair_info:
        placed = False

        for level_idx, intervals in enumerate(levels):
            overlap = any(
                not (pair["x2"] <= start or pair["x1"] >= end)
                for start, end in intervals
            )

            if not overlap:
                intervals.append((pair["x1"], pair["x2"]))
                pair["level"] = level_idx
                placed = True
                break

        if not placed:
            levels.append([(pair["x1"], pair["x2"])])
            pair["level"] = len(levels) - 1

        pair["y"] = top_value + BRACKET_START_GAP + pair["level"] * BRACKET_LEVEL_GAP
        placed_pairs.append(pair)

    if placed_pairs:
        y_upper = max(
            pair["y"] + BRACKET_HEIGHT + BRACKET_TEXT_OFFSET + 0.035
            for pair in placed_pairs
        )
    else:
        y_upper = top_value + 0.08

    return placed_pairs, y_upper


def interpret_posthoc(row):
    if row["reject_h0_holm"]:
        if row["mean_difference"] > 0:
            return f"{row['baseline_best_model']} significantly better"
        elif row["mean_difference"] < 0:
            return f"{row['comparison']} significantly better"

    return "no significant difference"


# ============================================================
# 5. LOAD INPUT DATA
# ============================================================

check_file_exists(DINO_CSV, "DINO3D")
check_file_exists(RESNET_CSV, "ResNet3D-18")
check_file_exists(FEATURES_CSV, "Features")

dino_df = load_family_data(DINO_CSV, "DINO3D")
resnet_df = load_family_data(RESNET_CSV, "ResNet3D-18")
features_df = load_family_data(FEATURES_CSV, "Features")

print("Input files loaded successfully.")
print("DINO3D:", DINO_CSV)
print("ResNet3D-18:", RESNET_CSV)
print("Features:", FEATURES_CSV)


# ============================================================
# 6. SELECT THE BEST EXPERIMENT PER FAMILY
# ============================================================

dino_best_df, dino_ranking, dino_best_name = select_best_experiment(
    dino_df,
    "DINO3D",
    MAIN_METRIC
)

features_best_df, features_ranking, features_best_name = select_best_experiment(
    features_df,
    "Features",
    MAIN_METRIC
)

resnet_best_df = resnet_df.copy()
resnet_best_name = "ResNet3D-18"

resnet_ranking = pd.DataFrame([{
    "raw_experiment_label": "ResNet3D-18",
    "mean": resnet_best_df[MAIN_METRIC].mean(),
    "std": resnet_best_df[MAIN_METRIC].std(ddof=1),
    "median": resnet_best_df[MAIN_METRIC].median(),
    "count": resnet_best_df[MAIN_METRIC].count(),
    "family": "ResNet3D-18"
}])


# ============================================================
# 7. BUILD DISPLAY LABELS
# ============================================================

dino_display_label = build_display_label("DINO3D", dino_best_name)
resnet_display_label = build_display_label("ResNet3D-18", resnet_best_name)
features_display_label = build_display_label("Features", features_best_name)

dino_best_df["display_label"] = dino_display_label
resnet_best_df["display_label"] = resnet_display_label
features_best_df["display_label"] = features_display_label

manual_display_order = [
    dino_display_label,
    resnet_display_label,
    features_display_label
]

selected_summary = pd.DataFrame([
    {
        "family": "DINO3D",
        "selected_experiment": dino_best_name,
        "display_label": dino_display_label,
        "selection_metric": MAIN_METRIC
    },
    {
        "family": "ResNet3D-18",
        "selected_experiment": resnet_best_name,
        "display_label": resnet_display_label,
        "selection_metric": MAIN_METRIC
    },
    {
        "family": "Features",
        "selected_experiment": features_best_name,
        "display_label": features_display_label,
        "selection_metric": MAIN_METRIC
    }
])

all_rankings = pd.concat(
    [dino_ranking, resnet_ranking, features_ranking],
    ignore_index=True
)

selected_summary_path = os.path.join(
    CSV_OUTPUT_DIR,
    f"selected_best_experiments_by_{MAIN_METRIC}.csv"
)

ranking_path = os.path.join(
    CSV_OUTPUT_DIR,
    f"ranking_by_family_{MAIN_METRIC}.csv"
)

selected_summary.to_csv(selected_summary_path, index=False, encoding="utf-8-sig")
all_rankings.to_csv(ranking_path, index=False, encoding="utf-8-sig")

print("\nSelected best experiments:")
display(selected_summary)

print("\nRanking by family:")
display(all_rankings)


# ============================================================
# 8. COMBINE THE SELECTED BEST MODELS
# ============================================================

combined_df = pd.concat(
    [dino_best_df, resnet_best_df, features_best_df],
    ignore_index=True
)

combined_df = combined_df.dropna(
    subset=["fold", "display_label"] + METRIC_COLS
).copy()

display_order = get_display_order(
    combined_df,
    MAIN_METRIC,
    manual_display_order
)

combined_df["display_label"] = pd.Categorical(
    combined_df["display_label"],
    categories=display_order,
    ordered=True
)

combined_df = combined_df.sort_values(
    ["display_label", "fold"]
).reset_index(drop=True)

combined_path = os.path.join(
    CSV_OUTPUT_DIR,
    f"combined_best_models_by_fold_{MAIN_METRIC}.csv"
)

combined_df.to_csv(combined_path, index=False, encoding="utf-8-sig")

print("\nCombined data:")
display(combined_df)

print("\nBoxplot order:")
print(display_order)


# ============================================================
# 9. SAVE BOXPLOT ORDER
# ============================================================

order_df = pd.DataFrame({
    "boxplot_order": display_order,
    "mean_main_metric": [
        combined_df.loc[
            combined_df["display_label"] == item,
            MAIN_METRIC
        ].mean()
        for item in display_order
    ]
})

order_path = os.path.join(
    CSV_OUTPUT_DIR,
    f"boxplot_order_{MAIN_METRIC}.csv"
)

order_df.to_csv(order_path, index=False, encoding="utf-8-sig")

print("\nBoxplot order table:")
display(order_df)


# ============================================================
# 10. SAVE SUMMARY STATISTICS
# ============================================================

summary_stats = (
    combined_df.groupby("display_label", observed=True)[METRIC_COLS]
    .agg(["mean", "std", "median", "min", "max", "count"])
)

summary_stats.columns = [
    "_".join(col).strip("_")
    for col in summary_stats.columns
]

summary_stats = summary_stats.reset_index()

summary_stats_path = os.path.join(
    CSV_OUTPUT_DIR,
    "summary_statistics_best_models.csv"
)

summary_stats.to_csv(summary_stats_path, index=False, encoding="utf-8-sig")

print("\nSummary statistics:")
display(summary_stats)


# ============================================================
# 11. CREATE BOXPLOTS WITH AUTOMATIC COHEN'S d BRACKETS
# ============================================================

sns.set_theme(style="whitegrid")


def make_comparison_boxplot(data, metric_col, display_order):
    metric_label = METRIC_LABELS.get(metric_col, metric_col)

    pivot_df = build_paired_matrix(
        data=data,
        metric_col=metric_col,
        order=display_order
    )

    if pivot_df.shape[0] < 2:
        print(f"[WARNING] Not enough paired folds for {metric_col}. Skipping plot.")
        return None, None

    effect_df = compute_pairwise_effects(
        pivot_df=pivot_df,
        metric_col=metric_col,
        display_order=display_order
    )

    pivot_path = os.path.join(
        CSV_OUTPUT_DIR,
        f"paired_matrix_best_models_{metric_col}.csv"
    )

    effect_path = os.path.join(
        CSV_OUTPUT_DIR,
        f"paired_cohens_d_best_models_{metric_col}.csv"
    )

    pivot_df.to_csv(pivot_path, encoding="utf-8-sig")
    effect_df.to_csv(effect_path, index=False, encoding="utf-8-sig")

    plot_df = pivot_df.reset_index().melt(
        id_vars="fold",
        value_vars=display_order,
        var_name="display_label",
        value_name=metric_col
    )

    plot_data_path = os.path.join(
        CSV_OUTPUT_DIR,
        f"plot_data_best_models_{metric_col}.csv"
    )

    plot_df.to_csv(plot_data_path, index=False, encoding="utf-8-sig")

    data_min = plot_df[metric_col].min()
    data_max = plot_df[metric_col].max()

    bracket_layout, y_upper_needed = compute_bracket_layout(
        effect_df=effect_df,
        display_order=display_order,
        top_value=data_max
    )

    y_lower = min(Y_AXIS_MIN, max(0.0, data_min - 0.05))
    y_upper = max(Y_AXIS_MAX, y_upper_needed)

    plt.figure(figsize=(PLOT_WIDTH, PLOT_HEIGHT))

    ax = sns.boxplot(
        data=plot_df,
        x="display_label",
        y=metric_col,
        order=display_order,
        width=0.5,
        showcaps=True,
        showfliers=False,
        boxprops=dict(
            facecolor="#d8ebff",
            edgecolor="#1f4e79",
            linewidth=1.8
        ),
        whiskerprops=dict(
            color="#1f4e79",
            linewidth=1.8
        ),
        capprops=dict(
            color="#1f4e79",
            linewidth=1.8
        ),
        medianprops=dict(
            color="#08306b",
            linewidth=2.4
        )
    )

    sns.stripplot(
        data=plot_df,
        x="display_label",
        y=metric_col,
        order=display_order,
        color="#0b3d91",
        size=6,
        alpha=0.75,
        jitter=0.10,
        ax=ax
    )

    ax.set_xlabel("Best model per approach", fontsize=13, fontweight="bold")
    ax.set_ylabel(metric_label, fontsize=13, fontweight="bold")
    ax.set_title(
        f"Best model comparison - {metric_label}",
        fontsize=15,
        fontweight="bold",
        pad=14
    )

    ax.set_ylim(y_lower, y_upper)

    plt.xticks(rotation=0, fontsize=10)
    plt.yticks(fontsize=10)

    ax.grid(axis="y", linestyle="--", alpha=0.25)
    ax.grid(axis="x", visible=False)

    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    for pair in bracket_layout:
        add_bracket(
            ax=ax,
            x1=pair["x1"],
            x2=pair["x2"],
            y=pair["y"],
            h=BRACKET_HEIGHT,
            text=pair["label"]
        )

    plt.tight_layout()

    plot_path = os.path.join(
        PLOT_OUTPUT_DIR,
        f"boxplot_best_models_with_automatic_cohens_d_{metric_col}.svg"
    )

    plt.savefig(plot_path, format="svg", bbox_inches="tight", dpi=300)

    plt.show()
    plt.close()

    print(f"\nSaved plot: {plot_path}")
    print(f"Saved paired matrix: {pivot_path}")
    print(f"Saved Cohen's d table: {effect_path}")

    return pivot_df, effect_df


all_effect_tables = []

for metric_col in METRIC_COLS:
    pivot_df_metric, effect_df_metric = make_comparison_boxplot(
        data=combined_df,
        metric_col=metric_col,
        display_order=display_order
    )

    if effect_df_metric is not None:
        all_effect_tables.append(effect_df_metric)

if all_effect_tables:
    all_effects_df = pd.concat(all_effect_tables, ignore_index=True)

    all_effects_path = os.path.join(
        CSV_OUTPUT_DIR,
        "paired_cohens_d_all_metrics.csv"
    )

    all_effects_df.to_csv(all_effects_path, index=False, encoding="utf-8-sig")

    print("\nAll Cohen's d results:")
    display(all_effects_df)


# ============================================================
# 12. FRIEDMAN TEST FOR THE MAIN METRIC
# ============================================================

main_pivot_df = build_paired_matrix(
    data=combined_df,
    metric_col=MAIN_METRIC,
    order=display_order
)

main_pivot_path = os.path.join(
    CSV_OUTPUT_DIR,
    f"friedman_paired_matrix_{MAIN_METRIC}.csv"
)

main_pivot_df.to_csv(main_pivot_path, encoding="utf-8-sig")

print("\nPaired matrix for Friedman:")
display(main_pivot_df)

if main_pivot_df.shape[0] < 2:
    raise ValueError("Not enough paired folds for Friedman test.")

if main_pivot_df.shape[1] < 3:
    raise ValueError("At least 3 experiments are required for Friedman test.")

friedman_stat, friedman_p = friedmanchisquare(
    *[main_pivot_df[col].values for col in main_pivot_df.columns]
)

ranks_per_fold = main_pivot_df.apply(
    lambda row: rankdata(-row.values, method="average"),
    axis=1,
    result_type="expand"
)

ranks_per_fold.columns = main_pivot_df.columns

avg_ranks_df = pd.DataFrame({
    "experiment": ranks_per_fold.columns,
    "average_rank": ranks_per_fold.mean(axis=0).values,
    f"mean_{MAIN_METRIC}": main_pivot_df.mean(axis=0).values,
    f"std_{MAIN_METRIC}": main_pivot_df.std(axis=0, ddof=1).values,
    f"median_{MAIN_METRIC}": main_pivot_df.median(axis=0).values
})

avg_ranks_df = avg_ranks_df.sort_values(
    ["average_rank", f"mean_{MAIN_METRIC}"],
    ascending=[True, False]
).reset_index(drop=True)

best_model = avg_ranks_df.iloc[0]["experiment"]

friedman_results = pd.DataFrame([{
    "metric": MAIN_METRIC,
    "n_folds": main_pivot_df.shape[0],
    "n_experiments": main_pivot_df.shape[1],
    "best_model_by_average_rank": best_model,
    "friedman_statistic": friedman_stat,
    "friedman_p_value": friedman_p
}])

friedman_path = os.path.join(
    CSV_OUTPUT_DIR,
    f"friedman_final_best_models_{MAIN_METRIC}.csv"
)

avg_ranks_path = os.path.join(
    CSV_OUTPUT_DIR,
    f"friedman_average_ranks_final_best_models_{MAIN_METRIC}.csv"
)

friedman_results.to_csv(friedman_path, index=False, encoding="utf-8-sig")
avg_ranks_df.to_csv(avg_ranks_path, index=False, encoding="utf-8-sig")

print("\nFriedman results:")
display(friedman_results)

print("\nAverage ranks:")
display(avg_ranks_df)


# ============================================================
# 13. POST HOC WILCOXON TEST WITH HOLM CORRECTION
# ============================================================

baseline_values = main_pivot_df[best_model].values
posthoc_rows = []

for exp in main_pivot_df.columns:
    if exp == best_model:
        continue

    comparison_values = main_pivot_df[exp].values

    try:
        stat, p_value = wilcoxon(
            baseline_values,
            comparison_values,
            zero_method="wilcox",
            alternative="two-sided",
            mode="auto"
        )
    except ValueError:
        stat = np.nan
        p_value = 1.0

    posthoc_rows.append({
        "metric": MAIN_METRIC,
        "baseline_best_model": best_model,
        "comparison": exp,
        "baseline_mean": np.mean(baseline_values),
        "comparison_mean": np.mean(comparison_values),
        "mean_difference": np.mean(baseline_values) - np.mean(comparison_values),
        "wilcoxon_statistic": stat,
        "p_value_raw": p_value
    })

posthoc_df = pd.DataFrame(posthoc_rows)

reject, pvals_corrected, _, _ = multipletests(
    posthoc_df["p_value_raw"].values,
    alpha=0.05,
    method="holm"
)

posthoc_df["p_value_holm"] = pvals_corrected
posthoc_df["reject_h0_holm"] = reject
posthoc_df["interpretation"] = posthoc_df.apply(interpret_posthoc, axis=1)

posthoc_path = os.path.join(
    CSV_OUTPUT_DIR,
    f"posthoc_wilcoxon_holm_final_best_models_{MAIN_METRIC}.csv"
)

posthoc_df.to_csv(posthoc_path, index=False, encoding="utf-8-sig")

print("\nPost hoc Wilcoxon + Holm:")
display(posthoc_df)


# ============================================================
# 14.
# BEST GLOBAL MODEL VS ALL OTHER MODELS
# ONE SEPARATE TABLE PER METRIC
# ============================================================

BASELINE_FAMILY = "DINO3D"
BASELINE_EXPERIMENT_TO_FIND = "SVM+2000"

PROFESSOR_TABLE_DIR = os.path.join(CSV_OUTPUT_DIR, "professor_tables")
os.makedirs(PROFESSOR_TABLE_DIR, exist_ok=True)


def clean_label_for_display(label):
    return str(label).replace("\n", " ").strip()


def normalize_label_for_search(label):
    label = str(label).lower()
    label = label.replace(" ", "")
    label = label.replace("_", "")
    label = label.replace("-", "")
    label = label.replace("\n", "")
    return label


def paired_cohens_d_for_table(baseline_values, comparison_values):
    differences = baseline_values - comparison_values
    mean_difference = np.mean(differences)
    std_difference = np.std(differences, ddof=1)

    if std_difference == 0:
        return np.nan, mean_difference

    cohens_d = mean_difference / std_difference
    return cohens_d, mean_difference


def interpret_effect_size(d):
    if pd.isna(d):
        return "undefined effect"

    abs_d = abs(d)

    if abs_d < 0.2:
        return "negligible effect"
    elif abs_d < 0.5:
        return "small effect"
    elif abs_d < 0.8:
        return "medium effect"
    else:
        return "large effect"


def interpret_professor_result(mean_difference, cohens_d, p_value, alpha=0.05):
    effect_text = interpret_effect_size(cohens_d)

    if pd.isna(p_value):
        return f"Wilcoxon not available; {effect_text}"

    if p_value < alpha:
        if mean_difference > 0:
            return f"Baseline model significantly better; {effect_text}"
        elif mean_difference < 0:
            return f"Comparison model significantly better; {effect_text}"

    return f"No significant difference; {effect_text}"


# ============================================================
# 14.1 BUILD DATAFRAME WITH ALL MODELS
# ============================================================

dino_all = dino_df.copy()
dino_all["display_label"] = (
    dino_all["family"].astype(str)
    + "\n"
    + dino_all["raw_experiment_label"].astype(str)
)

features_all = features_df.copy()
features_all["display_label"] = (
    features_all["family"].astype(str)
    + "\n"
    + features_all["raw_experiment_label"].astype(str)
)

resnet_all = resnet_df.copy()
resnet_all["display_label"] = "ResNet3D-18"

all_models_df = pd.concat(
    [dino_all, features_all, resnet_all],
    ignore_index=True
)

all_models_df = all_models_df.dropna(
    subset=["fold", "display_label"] + METRIC_COLS
).copy()


# ============================================================
# 14.2 FIND BASELINE MODEL
# ============================================================

candidate_baselines = []

for label in all_models_df["display_label"].unique():
    normalized_label = normalize_label_for_search(label)

    if normalize_label_for_search(BASELINE_FAMILY) in normalized_label:
        if normalize_label_for_search(BASELINE_EXPERIMENT_TO_FIND) in normalized_label:
            candidate_baselines.append(label)

if len(candidate_baselines) == 0:
    print("ERROR: Baseline model was not found.")
    print("\nAvailable model labels:")

    for label in sorted(all_models_df["display_label"].unique()):
        print("-", clean_label_for_display(label))

    raise ValueError(
        "Baseline model not found. Check BASELINE_FAMILY or BASELINE_EXPERIMENT_TO_FIND."
    )

baseline_model = candidate_baselines[0]

print("\nBaseline model selected for professor tables:")
print(clean_label_for_display(baseline_model))


# ============================================================
# 14.3 CREATE ONE TABLE PER METRIC
# ============================================================

METRIC_NAMES_FOR_TABLE = {
    "f1_macro": "Macro-F1",
    "f1_weighted": "Weighted-F1",
    "balanced_accuracy": "Balanced Accuracy"
}

professor_tables = {}
professor_paths = []

for metric_col in METRIC_COLS:

    pivot_df = all_models_df.pivot_table(
        index="fold",
        columns="display_label",
        values=metric_col,
        aggfunc="mean"
    )

    if baseline_model not in pivot_df.columns:
        raise ValueError(f"Baseline model not found in pivot table for {metric_col}")

    rows = []

    for comparison_model in pivot_df.columns:

        if comparison_model == baseline_model:
            continue

        paired_df = pivot_df[[baseline_model, comparison_model]].dropna()

        if paired_df.shape[0] < 2:
            continue

        baseline_values = paired_df[baseline_model].values
        comparison_values = paired_df[comparison_model].values

        cohens_d, mean_difference = paired_cohens_d_for_table(
            baseline_values,
            comparison_values
        )

        try:
            wilcoxon_statistic, wilcoxon_p_value = wilcoxon(
                baseline_values,
                comparison_values,
                zero_method="wilcox",
                alternative="two-sided",
                mode="auto"
            )
        except ValueError:
            wilcoxon_statistic = np.nan
            wilcoxon_p_value = np.nan

        rows.append({
            "Metric": METRIC_NAMES_FOR_TABLE.get(metric_col, metric_col),
            "Comparison": (
                f"{clean_label_for_display(baseline_model)} "
                f"vs {clean_label_for_display(comparison_model)}"
            ),
            "Mean difference": mean_difference,
            "Cohen's d": cohens_d,
            "Wilcoxon p-value": wilcoxon_p_value,
            "Interpretation": interpret_professor_result(
                mean_difference,
                cohens_d,
                wilcoxon_p_value
            )
        })

    metric_table = pd.DataFrame(rows)

    metric_table = metric_table.sort_values(
        by="Mean difference",
        ascending=False
    ).reset_index(drop=True)

    metric_table_rounded = metric_table.copy()
    metric_table_rounded["Mean difference"] = metric_table_rounded["Mean difference"].round(4)
    metric_table_rounded["Cohen's d"] = metric_table_rounded["Cohen's d"].round(4)
    metric_table_rounded["Wilcoxon p-value"] = metric_table_rounded["Wilcoxon p-value"].round(4)

    professor_tables[metric_col] = metric_table_rounded

    output_csv_path = os.path.join(
        PROFESSOR_TABLE_DIR,
        f"professor_table_{metric_col}.csv"
    )

    metric_table_rounded.to_csv(
        output_csv_path,
        index=False,
        encoding="utf-8-sig"
    )

    professor_paths.append(output_csv_path)

    print(f"\nProfessor table for {metric_col}:")
    display(metric_table_rounded)

    print("Saved CSV:")
    print(output_csv_path)


# ============================================================
# 14.4 SAVE ALL TABLES IN ONE EXCEL FILE WITH 3 SHEETS
# ============================================================

excel_output_path = os.path.join(
    PROFESSOR_TABLE_DIR,
    "professor_tables_best_model_vs_all_models.xlsx"
)

with pd.ExcelWriter(excel_output_path, engine="openpyxl") as writer:
    professor_tables["f1_macro"].to_excel(
        writer,
        sheet_name="Macro-F1",
        index=False
    )

    professor_tables["f1_weighted"].to_excel(
        writer,
        sheet_name="Weighted-F1",
        index=False
    )

    professor_tables["balanced_accuracy"].to_excel(
        writer,
        sheet_name="Balanced Accuracy",
        index=False
    )

print("\nProfessor tables saved in:")
print(PROFESSOR_TABLE_DIR)

print("\nExcel file with the 3 tables:")
print(excel_output_path)


# ============================================================
# 15. FINAL OUTPUT
# ============================================================

print("\nDONE.")
print("Final output folder:", OUTPUT_DIR)
print("CSV tables folder:", CSV_OUTPUT_DIR)
print("SVG plots folder:", PLOT_OUTPUT_DIR)
print("Professor tables folder:", PROFESSOR_TABLE_DIR)

print("\nMain files saved:")
print(combined_path)
print(selected_summary_path)
print(ranking_path)
print(summary_stats_path)
print(friedman_path)
print(avg_ranks_path)
print(posthoc_path)

print("\nProfessor table files saved:")
for path in professor_paths:
    print(path)

print(excel_output_path)